### ISSUE TITLE
Add support for extension OAuth 2.0 Authorization Grants

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#100]
Add a property to the OAuth 2.0 settings `extensionAuthorizationGrants`, which should be a list of any extension Authorization grant types supported by the Authentication server, since these can be anything that the OAuth vendor has defined, it is the vendor's responsibility to document how those should work.

```yaml
#%RAML 0.8
title: My Sample API
securitySchemes:
    - oauth_2_0:
        description: |
            OAuth 2.0 implementation.
        type: OAuth 2.0
        settings:
          authorizationUri: https://www.myapi.com/1/oauth2/authorize
          accessTokenUri: https://www.myapi.com/1/oauth2/token
          authorizationGrants: [ authorization_code, password ]
          extensionAuthorizationGrants: [ 'urn:ietf:params:oauth:grant-type:saml2-bearer' ]
```
