### ISSUE TITLE
Add the `signatures` property to the OAuth 1.0 settings

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#102]
RAML 1.0 should add one more property `signatures`, which should be a list of the signature methods used by the server. If this property is missing, it is assumed that the Authentication server allows any signature method defined in RFC5849.
Valid values for the signature methods are:
 - HMAC-SHA1
 - RSA-SHA1
 - PLAINTEXT

```yaml
#%RAML 0.8
title: My Sample API
securitySchemes:
    - oauth_1_0:
        description:|
            OAuth 1.0 continues to be supported for all API requests, but OAuth 2.0 is now preferred.
        type: OAuth 1.0
        settings:
          requestTokenUri: https://api.mysampleapi.com/1/oauth/request_token
          authorizationUri: https://api.mysampleapi.com/1/oauth/authorize
          tokenCredentialsUri: https://api.mysampleapi.com/1/oauth/access_token
          signatures: [ 'HMAC-SHA1', 'PLAINTEXT' ]
```
