### ISSUE TITLE
Remove lists for `<<` merge key

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#103]
The root level properties: `schemas`, `resourceTypes`, and `traits` are lists of dictionaries. User testing has demonstrated that lists are hard to write and read by humans.

We should make those properties, maps, and allow use of the merge operator to extend the list of traits, resource types, schemas, etc.

**IMPORTANT:** Since the [merge key](http://yaml.org/type/merge.html) in YAML is ambiguous in this case 

> RAML 1.0 should clarify that RAML processors should be able to parse more than one merge key operator per mapping

Example of a trait definition:

``` yaml
#%RAML 0.8
title: My Sample API
traits:
  secured:
    headers:
      Authorization:
        description: Send this header with the secret token
        example: Bearer 71543fa6a11044b0a9f3a8354ddcb00e
  searchable:
    queryParameters:
      q:
        description: The search string
```

Example of a trait definition, including traits remotely:

``` yaml
#%RAML 0.8
title: My Sample API
traits: !include http://myapi.com/raml/traits/traits.raml
```

Example of a trait definition, mixing local and remote traits:

``` yaml
#%RAML 0.8
title: My Sample API
traits:
  secured:
      headers:
        Authorization:
          description: Send this header with the secret token
          example: Bearer 71543fa6a11044b0a9f3a8354ddcb00e
  <<:
    !include http://myapi.com/raml/traits/traits.raml
  <<:
    !include http://myapi.com/raml/traits/moretraits.raml
```

In this last example, any trait declared in the `traits.yaml` will be added to the local traits. If a trait with the same name has been declared before, _it will not be overwritten_.
