### ISSUE TITLE
Internationalization for documentation

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#104]
By adding a `locales` root level property, and a keyword to reference text bundles, RAML 1.0 can provide support for localization of documentation.

A resource bundle is a YAML file, which contains a mapping, where each key is the name of a text resource, and each value is the value for that text resource string in a given locale.

``` yaml
#%RAML 0.8
title: !bundle title
locales:
  en_US: !include docs/en_US.bundle.yaml
  es: !include docs/es.bundle.yaml
/users:
  description: !bundle users.description
```

Where `docs/en_US.bundle.yaml` contains

``` yaml
title: My Sample API
users.description: The users resource provides access to all users in the system
```

Where `docs/en_US.bundle.yaml` contains

``` yaml
title: Mi API de ejemplo
users.description: El recurso users provee acceso a todos los usuarios en el sistema

```

RAML processors must pick the resource bundle which best matches the consumers locale.
