### ISSUE TITLE
Express parameter dependencies

### ISSUE THREAD

**Issue by dmartinezg** [raml-org/raml-spec#108]
To express some level of dependencies between named parameters we should add the following properties to the named parameter definitions:

| Property Name | Description |
| --- | --- |
| `dependsOn` | A list of named parameters which **must** be sent together with this named parameter. |
| `conflictsWith` | A list of named parameters which **must not** be used together with this named parameter. |
| `requiredIfNot` | This parameter expresses that the current named parameter is mandatory unless any of the other named parameters in the list is used. |

In the following example, the `lat` and `long` query parameters must be sent together unless the `location` named parameter is being sent.

``` yaml
title: My Sample API
/locations:
  get:
    queryParameters:
      lat:
        dependsOn: [long]
        requiredIfNot: [location]
        conflictsWith: [location]
      long:
        dependsOn: [lat]
        collidesWith: [location]
      location:
        requiredIfNot: [lat, long]
        conflictsWith: [lat, long]

```

With that configuration, the following requests are valid:
- `/locations?lat=1&long=2`
- `/locations?location=1,2`

The following should be rejected:
- `/locations` (rejected because `requireIfNot` is not satisfied )
- `/locations?location=1,2&lat=1` (rejected because `conflictsWith` is not satisfied)
- `/locations?location=1,2&long=1` (rejected because `conflictsWith` is not satisfied)
- `/locations?lat=1` (rejected because `dependsOn` is not satisfied)
- `/locations?long=1` (rejected because `dependsOn` is not satisfied)

These properties cannot be used on URI parameters, as all URI parameters are mandatory.
