### ISSUE TITLE
Allow to specify a schema element in a larger schema

### ISSUE THREAD

**Issue by dmartinezg** [raml-org/raml-spec#109]
When specifying a request or response body's schema using JSON or XML schema, the `schema` property may point to a schema definition which may contain more than a single object or resource.

We should update the `body` definition by making the schema property include the name of the element in case of XML-schema, the object id in case of JSON-Schema, or an arbitrary identifier in case of another type of schema.

| Property Name | Description |
| --- | --- |
| objectIdentifier | If `type` is `json-schema/draft-03` or `json-schema/draft-04`, it should be the object id URI. If the `type` is xml-schema, it should be the name of the `element`. |

``` yaml
bodies:
  user:
    schema:
      type: json-schema/draft-04
      definition: |
        {
            "id": "http://my.sample.api/user-schema",
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "properties": {
                "name": {}
            },
            "required": [ "name" ]
        }
      objectIdentifier: http://my.sample.api/user-schema
```

``` yaml
bodies:
  user:
    schema:
      type: xml-schema
      definition: |
        <?xml version="1.0" encoding="UTF-8" ?>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
          <xs:element name="shiporder">
            <xs:complexType>
              <xs:sequence>
                ...
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:schema>
      objectIdentifier: shiporder
```
