### ISSUE TITLE
Raml should allow for global example declarations to reduce verbosity

### ISSUE THREAD

**Issue by natalia-garcia** [raml-org/raml-spec#11]
I would like raml to allow for global example definitions. Otherwise I am forced to fill out the very hierarchy I avoid when using global schema definitions and resourceTypes.
For example. Given the resourceType:

``` yaml
collection:
  type: base
  post:
    body:
      schema: post-<<resourcePathName | !singularize>> # e.g. post-sale
```

I can now reference schema automatically for all collection resources in my hierarchy. However, when I want to provide an example for a method on a collection I am forced to fill out the hierarchy. For example:

```
  /sales:
    type: collection
    post:
      body:
        example: |
          Unknown macro: { "machineId" }
    get:
      responses:
        201:
          body:
            example: |
              Unknown macro: { "count" }
```

which could have been avoided with a mere reference to a global example at the resourceType definition. For example:

```
collection:
  type: base
  post:
    body:
      schema: post-<<resourcePathName | !singularize>> # e.g. post-sale
      example: post-<<resourcePathName | !singularize>>-example
```
