### ISSUE TITLE
Add a simple way to add custom metadata to the root level, resources and methods in a RAML spec

### ISSUE THREAD

**Issue by dmartinezg** [raml-org/raml-spec#110]
RAML 1.0 should have a way to include extension data that is meant for specific RAML processors.

This will allow RAML files to provide extra semantics meant for specific RAML processors, such as custom validations, expected exceptions, implementation details, etc.

`metadata` is a property which can be used at the root level, at the resource level or at a method level. It is a mapping, which can contain any arbitrary data. Custom documentation MUST accompany this RAML definition in order to understand how to interpret that custom metadata. This spec should not provide a way to interpret that metadata.

```yaml
title: My Sample API
metadata:
  mantainer: apimaster@my.sample.api
/users:
  post:
    metadata:
      handlerImplementation: UserController.create
  get:
    metadata:
      handlerImplementation: UserController.search
```
