### ISSUE TITLE
Use YAML syntax to express JSON schemas

### ISSUE THREAD

**Issue by dmartinezg** [raml-org/raml-spec#116]
As JSON has a 1-1 mapping to YAML, RAML should take advantage of this to simplify the writing of JSON schemas, by allowing them to be written in YAML instead of JSON.

The following examples, should be semantically identical:

```yaml
#RAML 1.0
title: My sample API
bodies:
  user:
    schema:
      type: json-schema/draft-04
      definition: 
        id: http://my.sample.api/user-schema
        $schema: http://json-schema.org/draft-04/schema#
        type: object
        properties:
          name: {}
        required:
          - name
      objectIdentifier: http://my.sample.api/user-schema
```

```yaml
#RAML 1.0
title: My sample API
bodies:
  user:
    schema:
      type: json-schema/draft-04
      definition: |
        {
            "id": "http://my.sample.api/user-schema",
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "properties": {
                "name": {}
            },
            "required": [ "name" ]
        }
      objectIdentifier: http://my.sample.api/user-schema
```
