### ISSUE TITLE
Allow arrays for baseURI

### ISSUE THREAD

**Issue by vanto** [raml-org/raml-spec#119]
We describe an API that has three endpoints, which are basically DEV, QA and PROD environments. It would be nice if RAML would allow to document all these three APIs directly by allowing to take an array in addition to a string for the baseURI field.

Example:
```yaml
#%RAML 0.8
title: foo API
version: v1
baseUri: 
  - https://dev.bar.com/api/{version}
  - https://qa.bar.com/api/{version}
  - https://prod.bar.com/api/{version}
```
