### ISSUE TITLE
Add testing capabilities to spec

### ISSUE THREAD

**Issue by mikestowe** [raml-org/raml-spec#120]
Let users define user tests within the spec so that user's can utilize RAML as an all-in-one, defining their API, defining its behaviors, and allowing them to generate documentation and unit tests - ensuring that they follow spec driven development instead of creating behaviors outside of the spec.

Example:

``` yaml
/resource:
   get:
      tests:
          /
          head:
               ResponseCode:
                   IsEqual: 200
                   IsNotEqual: 400
                   Contains: 2
          body:
              application/json:
                  DoesNotContain: Jim
                  Contains: Bob

          /{id}:
              body:
                  application/json:
                      Contains: Joe
                  application/xml:
                      Contains: <name>Joe</name>
```
