### ISSUE TITLE
Add `logo` as root parameter

### ISSUE THREAD

**Issue by aldonline** [raml-org/raml-spec#127]
RAML documentation generators can then use this parameter to generate customized documentation.
This would benefit API developers and consumers.

``` yaml
#%RAML 0.8
title: My API
version: v3
logo: http://example.com/logo.png
```

Suggested dimensions: 300px square.
- The square makes it easy to use the logo both vertically and horizontally.
- The square format is an industry standard. Initially for user avatars but more and more sites require the format for companies as well ( twitter, facebook, github, angel list, etc )
