### ISSUE TITLE
Parameters for optional Resource Type properties should also be optional

### ISSUE THREAD

**Issue by ex-nerd** [raml-org/raml-spec#143]
The spec currently states:

_The definitions of resource types and traits MAY contain parameters, whose values MUST be specified when applying the resource type or trait ..._

This means that Resource Type parameters are currently mandatory, even if they're not being used.  Given a snippet like this:

```yaml
# ...
resourceTypes:
  - Resource:
      get:
        description: Get one <<ResourceName>> record.
      patch?:
        description: Some info about <<TextAboutPatch>>.
# ...
```

In the case of a resource with no `patch` support, I still have to provide a blank `TextAboutPatch` property:

```yaml
/MyThing
  type:
    Resource:
      ResourceName: MyThing
      TextAboutPatch:
  get:
    description: Override the default Resource description here.
```

It would be nice if the spec would allow for parameters to be optional if their corresponding resource type properties are unused for the given resource.
