### ISSUE TITLE
Allow multiple `baseUri` values

### ISSUE THREAD

**Issue by ex-nerd** [raml-org/raml-spec#150]
For consideration in 1.0:

It would be very helpful for enterprise APIs with multiple environments (e.g. dev, test, staging, prod) to be able to specify all of these via a `baseUri` key/value property.  I would recommend keeping the legacy behavior:

```yaml
baseUri: https://api.example.com/{version}
```

but also adding an allowance for a more complex setup with arbitrary key names:

```yaml
baseUri: 
    dev: https://dev.api.example.com/{version}
    qa: https://qa.api.example.com/{version}
    prod: https://api.example.com/{version}
```
