### ISSUE TITLE
Arrays cannot be used as query parameters

### ISSUE THREAD

**Issue by joshavant** [raml-org/raml-spec#152]
I'd like to have the ability to specify an `array`-type query parameter.

Currently, only `string`, `number`, `integer`, `file`, `date`, and `boolean` are possible values for a `queryParameter`'s `type`.

It seems like the `type` parameter should reasonably adopt the set of possible JSON data types, since many RAML users are using it to represent JSON.

I'm also unable to use Markdown in the `example` value for this parameter, so I don't have a way to aesthetically present example data, either.

**Comment by econchick** [comment]
Hi @joshavant (side note: I'm not affiliated with raml.org or the spec, just a user).

Would [enums](http://raml.org/spec.html#enum) address your issue?  I use it in this fashion:

```
/someendpoint:
    displayName: some-endpoint
    get:
      description: GET some info from some endpoint
      securedBy: [ oauth_2_0: {scopes: ['endpoint-read']} ]
      queryParameters:
        sometype:
          displayName: Some Item Type
          description: The item type to get.
          type: string
          example: footype
          enum: ["footype", "bartype"]
          required: true
```
