### ISSUE TITLE
Suggestion: json schema for more flexible queryParameters

### ISSUE THREAD

**Issue by redben** [raml-org/raml-spec#162]
Sorry if this is not the right place for suggestions...

Wouldn't it be helpfull to be able to define queryParameters in (json) schema (or subset)
##### multiple query parameter groups

An api that allows searching _either_ by location name _or_ by lat/long/radius

`/points-of-interest?location=barcelona`
`/points-of-interest?lat=41.3833&long=2.1833&radius=5`

A "work around" currently is to declare none as required and in description say that if location is present, lat/long/radius are ignored. But one still can't enforce that 1 of both sets is required.

**EDIT** candidate #108 tacles this issue (with new directives)

If queries where defined in json schema you could have:

``` yaml
queryParameters:
    oneOf:
        - description: search by location
          required: ["location"]
          properties:
            location:
        - description: search by coordinates
          required: ["lat","long","radius"]
          properties:
            lat:
            long:
            radius:
```
#### Other benefits

As far as I know all the directives used to define query parameters in raml can be covered by json schema. `repeat` could be used as it is defined today in raml (json schema being ok with custom properties)
Or it could be defined as an array (and leverage `minItems` `maxItems` `uniqueItems`...etc

example of a hotel booking api that can quote up to 4 rooms

``` yaml
queryParameters:
    roomOccupancy:
        description: array where each item represents a room occupancy (number of guests in the room)
        examples:
          - ?roomOccupancy=2
          - ?roomOccupancy=2&roomOccupancy=1
        type: array
        minItems: 1
        maxItems: 4
        items:
            description: number of guests for this room
            type: integer
            minimum: 1
            maximum: 3
```
