### ISSUE TITLE
allow arrays as parameters

### ISSUE THREAD

**Issue by nialdarbey** [raml-org/raml-spec#17]
I'd like to parameterize a trait so that instead of:

```yaml
orderBy:
          description: Order by field
          type: string
          enum: [lastUpdated, name, createdAt]
          required: false
```

I have 

```yaml
orderBy:
          description: Order by field
          type: string
          enum: << values >>
          required: false
```
