### ISSUE TITLE
Allow Expressing Examples in YAML 

### ISSUE THREAD

**Issue by usarid** [raml-org/raml-spec#172]
It's often much easier to deal with YAML when describing the payload. 

E.g.:
```
#%RAML 1.0
title: API with Examples
types:
  User:
    type: object
    properties:
      name: string
      lastname: string
    example:
      name: Bob
      lastname: Marley
  Org:
    type: object
    properties:
      name: string
      address?: string
    examples:
      - name: Acme
      - name: Software Corp
        address: 35 Central Street
```
