### ISSUE TITLE
Resource Types and Traits optional structures inheritance rules for scalars

### ISSUE THREAD

**Issue by dmartinezg** [raml-org/raml-spec#20]
The spec says that any property in an RT or trait, to which a "?" is appended, becomes optional, and its value is only composed if the target resource has the property.

What then of properties which are scalars and have a null value. In the following example, what should be the output?

``` yaml
#%RAML 0.8
title: Some API
resourceTypes:
  - resourceType1:
      description?: Some Description
/res:
  type: resourceType1
  description:
```

In my opinion, optional flags should apply only to structures, if it does, the RAML above is incorrect, and processors should emit an error.
