### ISSUE TITLE
date format:  RFC 2616 vs. RFC 3339

### ISSUE THREAD

**Issue by gardea** [raml-org/raml-spec#202]
Is there a particular reason why RFC 2616 was recommended over RFC 3339? I understand the differences between the two; however, there's a strong community believing that ISO 8601 derived formats (RFC 3339 being one) should be the only format used. It would also promote wire level interoperability with other stacks, which at this time seems to predominantly favour 3339...

**Comment by sichvoge** [comment]
There is no particular reason. We have seen some buzz around that ISO format and we can still easily change it to RFC 3339. Would that be better?

https://github.com/raml-org/raml-spec/issues/15

**Comment by gardea** [comment]
I personally consider it would be much better. I also have to disclose that I am heavily influenced by current (large scale) deployments of RAML that we are involved in, the tooling we've built, and our interoperability requirements (XSD to RAML/JSON Schema - XSD is based on ISO8601; RAML to and from Swagger 2.0).

**Comment by sichvoge** [comment]
Would it be better to change it to ISO8601 or RFC3339? (sorry if that is the same, but I understand it is not. RFC3339 is just a kind of ISO8601, right?)

**Comment by gardea** [comment]
You are correct: RFC 3339 is a "simplification" of ISO 8601. My vote goes to RFC 3339.

**Comment by robertlevy** [comment]
+1

**Comment by sichvoge** [comment]
ok cool - accepted. we will change it to RFC 3339

**Comment by mj1856** [comment]
RFC3339 is great, for *timestamps*.  However, it does not cover date-only, time-only, or datetime-without-timezone-offset values.  Those are all covered by ISO 8601.  RAML should specify the ISO8601 *extended format* in general, and can further clarify conformance to RFC3339 for timestamps.

This is relevant, considering #105.

**Comment by mj1856** [comment]
And RFC 822 / 2816 / 2822, et. al. is definitely the wrong choice.  All modern APIs are gravitating to ISO8601 / RFC3339, for many good reasons.

**Comment by usarid** [comment]
We cannot just change to RFC3339 without giving some thought to current users of RAML 0.8 and moreover to users of HTTP :-)

For example, a user of RAML 0.8 that had described a header field as being of type `date` upgrades to 1.0, and now what? How do they migrate? Their spec is now valid 1.0 but doesn't describe their API, as the header values are now invalid. What can they do?

Can they describe their existing API in 1.0? Not well, because our date type has no standard way (`format` only applies to numbers, at this moment). They could use a string with a regexp, perhaps, and they could use a string with annotations, but this is clearly working against the grain.

Can they change their API? Probably not, because 1) their clients and their developers don't want to do it without a good reason, and 2) the HTTP standard dictates that standard datetime header fields have the format in RFC2616 (the HTTP standard) which we chose in RAML 0.8. 

Staying with the RFC2616 format as the only one isn't any better, e.g. because of JSON Schema and XML Schema compatibility -- not that RAML types have to match them, but they need to accommodate wide swaths of data that in the past has been validated by JSON and XML Schema. 

For the record, HTTP headers (the one place I know of where HTTP makes a comment on datetime formats, via RFC2616) must be in RFC2616 format; XML Schema's dateTime type is in one specific subset of ISO8601, and JSON Schema uses the RFC3339 profile of ISO8601. None of them allows the full ISO8601. Our goal with RAML types is to have the same way of specifying bodies as well as query parameters, headers, and URI parameters, so we must be cognizant of all these.

It seems like we should consider allowing the `format` facet to apply to dates too, with a couple of built-in recognized values (`rfc2616` and `rfc3339`, where the latter is the default), and a way to roll your own, e.g. other values would be allowed for `format` but would have no pre-defined meaning, and/or specifying a regexp via a `pattern` (and `format` and `pattern` would be mutually exclusive). The resulting construction would be along the lines of:

```yaml
created:
  type: date
  format: rfc3339   # The default, so optional to specify it
last-modified:
  type: date
  format: rfc2616   # For HTTP headers, e.g.
revised:
  type: date
  format: millis   # It's a date, but its format is only specified by processors who know what this is
received:
  type: date
  format: iso8601   # It's again a date, but we don't enforce processors must support all of ISO8601
accepted:
  type: date
  pattern: "dddd-dd-dd"  # It's a date, whose representation matches this regexp - no information about the meaning of the matched pattern
```
