### ISSUE TITLE
Support for multiple names for one query parameter

### ISSUE THREAD

**Issue by samekmichal** [raml-org/raml-spec#212]
Is to possible in RAML 1.0 to specify one query parameter with two distinct names?

Example:
```
?query=raml
~~
?q=raml
```

**Comment by usarid** [comment]
Those are two separate query parameters, but they can share the same definition in the spec, by coming from the same trait or resource type, by coming from a common !include, or by simply pointing from one to the other with a YAML reference.






On Thu, Dec 17, 2015 at 12:27 AM -0800, "Michal Samek" <notifications@github.com> wrote:












Is to possible in RAML 10 to specify one query parameter with two distinct names?



Example:

?query=raml
~~
?q=raml

**Comment by samekmichal** [comment]
Thank you for the response. I think YAML reference is what I should go for, however, I am not sure if I get that right, is this how that could be accomplished?
```
traits:
  searchable:
    queryParameters:
      q: *queryParamFull
      query: &queryParamFull
        displayName: a query parameter
        description: ...
        type: string
```

Thanks!
