### ISSUE TITLE
Typo in section Runtime Polymorphism (Discriminators) 

### ISSUE THREAD

**Issue by samekmichal** [raml-org/raml-spec#214]
If I understand `discriminators` correctly there is a typo in one example.

```
#%RAML 1.0 
title: My API With Types
types:
  Person:
    type: object
    discriminator: kind
    properties:
      name: string
      kind: string
  Employee:
    type: Person
    discriminatorValue: employee
    properties:
      employeeId: string
  User:
    type: Person
    discriminatorValue: person <<< user
    properties:
      userId: string
```

```
#%RAML 1.0 
data:
  - name: A User
    userId: 111
    kind: user
  - name: An Employee
    employeeId: 222
    kind: employee
```

I believe the `discriminatorValue` for class `User` shall be `user` not `person`.
