### ISSUE TITLE
Any plans on having RequiredIf

### ISSUE THREAD

**Issue by tanertopal** [raml-org/raml-spec#215]
Is there any plan on having RequiredIf for type properties. So this could be done:
```
  Player:
    type: object
    properties:
      kind:
        type: string
        enum: [anonymous, user]
      user:
        type: user-types.User
        requiredIf: kind == user
```
or is there already some way to realize this?
