### ISSUE TITLE
Provide different examples based on input values

### ISSUE THREAD

**Issue by jantoniucci** [raml-org/raml-spec#281]
Add support to specify different examples on resources based on input values: uri parameter, query parameters, headers, etc.

A naif proposal:

```yaml
#%RAML 1.0
title: PoC on examples including inputs
version: v1
protocols: [ HTTPS ]
baseUri: /api/{version}
mediaType: application/json
/foos/{fooId}:
  uriParameters:
    fooId:
      type: integer
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              name: string
              age?: integer
            examples:
              foo1:
                description: when is called as /foos/1
                uriParameters:
                  fooId: 1
                content:
                  name: "foo1"
                  age: 1
              foo2:
                description: when is called as /foos/2
                uriParameters:
                  fooId: 2
                content:
                  name: "foo2"
                  age: 2
```

**Comment by usarid** [comment]
That's pretty cool!
Let's not put it into 1.0 at this late stage, but rather pursue the idea through annotations and see if we can come to a relatively general solution to this long-standing and important need, then consider standardizing it in a future version of RAML.






On Tue, Mar 8, 2016 at 3:13 AM -0800, "Javier Antoniucci" <notifications@github.com> wrote:












Add support to specify different examples on resources based on input values: uri parameter, query parameters, headers, etc.



A naif proposal:

#%RAML 1.0
title: PoC on examples including inputs
version: v1
protocols: [ HTTPS ]
baseUri: /api/{version}
mediaType: application/json
/foos/{fooId}:
  uriParameters:
    fooId:
      type: integer
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              name: string
              age?: integer
            examples:
              foo1:
                description: when is called as /foos/1
                uriParameters:
                  fooId: 1
                content:
                  name: "foo1"
                  age: 1
              foo2:
                description: when is called as /foos/2
                uriParameters:
                  fooId: 2
                content:
                  name: "foo2"
                  age: 2

**Comment by jantoniucci** [comment]
It's very usefull to feed a mock server with input driven examples, please vote it!

**Comment by usarid** [comment]
You can absolutely do that, just define annotation types that your mocking server will recognize.






On Wed, Mar 9, 2016 at 7:52 AM -0800, "Javier Antoniucci" <notifications@github.com> wrote:












It's very usefull to feed a mock server with input driven examples, please vote it!

**Comment by jantoniucci** [comment]
Oh, yes! This is the way I am taking (see next raml example) but I am looking for a standardized one.

```
#%RAML 1.0
title: PoC on examples including inputs
version: v1
protocols: [ HTTPS ]
baseUri: /api/{version}
mediaType: application/json
annotationTypes:
  exampleInput: !include annotations/example-input.raml
/foos/{fooId}:
  uriParameters:
    fooId:
      type: integer
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              name: string
              age?: integer
            examples:
              foo1:
                (exampleInput):
                  inputType: uriParam
                  inputName: fooId
                  inputValue: "1"
                description: foo1
                content:
                  name: "foo1"
                  age: 1
              foo2:
                (exampleInput):
                  inputType: uriParam
                  inputName: fooId
                  inputValue: "2"
                description: foo2
                content:
                  name: "foo2"
                  age: 2
```

**Comment by usarid** [comment]
Mainly because we need to draw the line somewhere to be able to say we have a complete list of features for RAML 1.0 and publish it (and its parsers) -- hard for anyone to build on a spec that evolves continuously.






On Wed, Mar 9, 2016 at 7:59 AM -0800, "Javier Antoniucci" <notifications@github.com> wrote:












Oh, yes! This is the way I am taking (see next raml example) but I am looking for a standardized one.

#%RAML 1.0
title: PoC on examples including inputs
version: v1
protocols: [ HTTPS ]
baseUri: /api/{version}
mediaType: application/json
annotationTypes:
  exampleInput: !include annotations/example-input.raml
/foos/{fooId}:
  uriParameters:
    fooId:
      type: integer
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              name: string
              age?: integer
            examples:
              foo1:
                (exampleInput):
                  inputType: uriParam
                  inputName: fooId
                  inputValue: "1"
                description: foo1
                content:
                  name: "foo1"
                  age: 1
              foo2:
                (exampleInput):
                  inputType: uriParam
                  inputName: fooId
                  inputValue: "2"
                description: foo2
                content:
                  name: "foo2"
                  age: 2

**Comment by jantoniucci** [comment]
Absolutely! And all of you are doing an excellent work very appreciated by all of us. Thanks!

**Comment by usarid** [comment]
Thank **you** for the suggestion and the support!

**Comment by chrpinedo** [comment]
I would add to this suggestion to be able to provide not only different example but also different responses (200/400/.., schemas, ...) based on the input values (uri parameter, query parameters, headers, etc.).

**Comment by freddrake** [comment]
I think a specification that addresses this topic would be very welcome, and give API specifications and tool builders a common language. (A better situation that having several similar but not-quite-parallel specifications thrown together by tool developers.)

However, it can reasonably be implemented as an extension using annotations.  While RAML 1.0 is fresh, that's only because it's already been through an evolutionary & consensus building process.  The new set of capabilities you describe would just be starting.  Being able to evolve in parallel seems valuable, at least until both are considered stable.  And once you hit that point, you don't need to merge them.

**Comment by jantoniucci** [comment]
Yes, actually we are using the following annotation that is enough flexible to define uri, params, body and headers inputs. 

Nevertheless, I prefer a standard solution from the RAML specification. This will add maturity and common language.

```
#%RAML 1.0 AnnotationTypeDeclaration
displayName: exampleInput
description: input values for an example
allowedTargets: NamedExample
usage: define inputs to activate an specific examples declaring param types, names and values
type: array
items:
  properties:
    inputType:
      description: defines the input type (uriParam, queryParam, header, body), fill the input type using as values uriParam, queryParam, header or body
      enum: [ uriParam, queryParam, header, body ]
      required: true
    inputName:
      type: string
      description: defines the input name, fill the input name using the uri param name, query param name, etc exactly as is defined in the resource
      required: true
    inputValue:
      type: string
      description: defines the input value, fill the input name using the value to be checked
      required: true
```
