### ISSUE TITLE
Map declaration is not yaml 1.2 compliant

### ISSUE THREAD

**Issue by robvanmieghem** [raml-org/raml-spec#286]
Map declaration (https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md#map-types):
```
#%RAML 1.0
title: My API With Types
types:
  MapOfNumbers:
    type: object
    properties:
      []:
        type: number
```

The standard golang yaml parser bails with the following error:

`yaml: invalid map key: []`

The online yaml parser http://yaml-online-parser.appspot.com bails with the following error:
```
ERROR:

while constructing a mapping
found unacceptable key (list objects are unhashable)
```

I suggest to drop this way of declaring maps since the inline map declarations are a lot nicer anyway:
```
#%RAML 1.0
title: My API With Types
types:
  MapOfNumbers:
    type: number{}
```

**Comment by sichvoge** [comment]
I do agree that this semantic shortcut is quite helpful, but we should be consistent with our approach to have an extended version and a shortcut. What do you think about using the following notation:

```yaml
#%RAML 1.0
title: My API With Types
types:
  MapOfNumbers:
    type: object
    properties:
      "[]":
        type: number
```

**Comment by robvanmieghem** [comment]
That's indeed a lot better, this also works with https://github.com/raml-org/raml-js-parser-2

I think it would be good to update the spec and documentation to use `"[]"` instead of `[]`

**Comment by sichvoge** [comment]
@robvanmieghem it's strange that YAML parser is complaining actually. According to the spec any key inside a map can be again a node. So theoretically sequences should be supported. :/

**Comment by petrochenko-pavel-a** [comment]
>I think it would be good to update the spec and documentation to use "[]" instead of []
@robvanmieghem , I agree. Currently we have an  ugly border case in the parser to support []

**Comment by robvanmieghem** [comment]
> it's strange that YAML parser is complaining actually. According to the spec any key inside a map can be again a node. So theoretically sequences should be supported. :/

@sichvoge I don't want to start a discussion on the yaml spec interpretation here but it is a fact that most yaml parsers do not accept this syntax as being valid. For a spec as RAML I think it is not a good idea to use a border case since this will not improve RAML adoption and compatibility.

**Comment by usarid** [comment]
I agree, and I think having `"[]"` is possibly even worse (who's going to remember that?), so perhaps we should find another notation...

**Comment by sichvoge** [comment]
@robvanmieghem any perspective on an alternative notation or do you think that `"[]"` is simple enough?

**Comment by usarid** [comment]
Let's change the RAML 1.0 data types spec as follows:

By default a map can have additional properties beyond those specified in its data type. To restrict those, one may either use a facet called `additionalProperties`, whose value is *always* a boolean (not a map), by setting `additionalProperties: false`, or by specifying regular expression patterns that matches sets of keys and restricts their values: these are called "pattern properties". The patterns are delineated by pairs of opening and closing `/` characters, as follows:
```raml
types:
  recipient:
    type: object
    properties:
      name: string
      address: string
      /^note\d+$/: string
```
This restricts any additional properties whose keys start with "note" followed by one or more digits to be a string.

To force all additional properties to be strings, regardless of their keys, use:
```raml
types:
  recipient:
    type: object
    properties:
      name: string
      address: string
      //: string
```

This is the only way to specify pattern properties: we will not have a `patternProperties` facet, to avoid bloat.

Moreover, if `additionalProperties` is `false` (explicitly or by inheritance) in a given type definition, then pattern properties are not allowed to be set explicitly in that definition. If it is true (or omitted) in a given type definition, then pattern properties are allowed and further restrict the allowed additional properties in that type.

**Comment by sichvoge** [comment]
That makes a lot sense. According to this @usarid it seems the "Map Type" chapter is misleading and therefore not necessary anymore; as well as the shortcut for it `number{}`. The core of the initial proposal is actual related to an object type and the ability to have additional properties on an type instance that are either always valid (`additionalProperties: true`), valid if the name of the property is valid against a pattern (`additionalProperties: true` + `/^note\d+$/: string`), or not allowed (`additionalProperties: false`). So for example having the following type definition:

```yaml
types:
  recipient:
    type: object
    properties:
      name: string
      address: string
```

This example of an instance is fully valid:

```yaml
recipient:
  name: "Pavel"
  address: "Russia"
  age: 35
```

---------------

Restricting all additional properties to string by adding `//: string` should make the example invalid.

```yaml
types:
  recipient:
    type: object
    properties:
      name: string
      address: string
      //: string
```

```yaml
recipient:
  name: "Pavel"
  address: "Russia"
  age: 35 # invalid as the value of `age` is not an integer
```

But

```yaml
recipient:
  name: "Pavel"
  address: "Russia"
  note: "Developer" # fully valid
```

------------------

To make the first example valid again you only need to add a pattern to restrict only certain properties to be a string

```yaml
types:
  recipient:
    type: object
    properties:
      name: string
      address: string
      /^note\d+$/: string
```

```yaml
recipient:
  name: "Pavel"
  address: "Russia"
  age: 35 # valid as it does not match the pattern
```

```yaml
recipient:
  name: "Pavel"
  address: "Russia"
  age: 35 # valid
  note: "Developer" # valid
```

**Comment by robvanmieghem** [comment]
For what it is worth, I like the solution and the new map declaration in the spec, good job!

**Comment by iwanbk** [comment]
From what i have read, it seems that map type can only be defined by:

- setting `additionalProperties` facet to false
- Only have one pattern properties.

example
```
types:
  mapOfString:
    type: object
    additionalProperties: false
    properties:
      //: string
```

@sichvoge CMIIW

**Comment by sichvoge** [comment]
There is actually no map type. The old "map type" was related to additional properties only. See [here](https://github.com/raml-org/raml-spec/blob/raml-10-rc2/versions/raml-10/raml-10.md#additional-properties) for more information. 

But if you add `additionalProperties` to `false` you will actually never be able to add any (thats what `//` means) property to an instance of `mapOfString`.

Not sure if that answers your question if there is any :)

**Comment by iwanbk** [comment]
@sichvoge 
Thanks, for clarification, if i want to define a map with key = string and value = int, i need to write this
```
types:
  mapOfInt:
    properties:
      //: int
```

**Comment by sichvoge** [comment]
The notion of `//` is more about having additional properties in a type instance than you defined. So lets assume you have the following type:

```yaml
Person:
  properties:
    name: string
```

A valid instance of this type for example is:

```
--- data
Person:
  name: Christian
```

but also

```
--- data
Person:
  name: Christian
  age: 15 # an additional properties
```

If you want to declare that all additional properties are integer and nothing else (so no string for example), you can use `//` to do that.

```yaml
Person:
  properties:
    name: string
    //: integer
```

If you want to further restrict saying that all the additional properties needs to match a certain pattern, you can put the pattern in between the two slashes; for example `/^note\d+$/`.

Does that clarify your question?
