### ISSUE TITLE
What is a partial method or resource?

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#304]
In RAML 0.8 and 1.0 we define a trait or resource type as "partial method/resource", be don't really specify what this "partial" inherits.

My initial concern about that and looking at different implementation is that, for example, some support to define `is` in a trait and some aren't. The spec is not clear about that.

```yaml
traits: 
  test:
    is: [ pageable ]
  pageable:
```

I am fine with either, but we should be more explicit on what "partial" means, or even if we need to mention that it is partial.

**Comment by sichvoge** [comment]
We should also think about if we really want to allow inheritance on trait level since we have composition already.

```yaml
traits: 
  test:
    is: [ pageable ]
  pageable:
```

vs

```yaml
traits: 
  test:
  pageable:
/resource:
  is: [ pageable, test ]
```
