### ISSUE TITLE
Remove `discriminator` from any union type definition

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#307]
In RAML 1.0 RC1 you are able to define a discriminator for union types. This could introduce a lot of ambiguity when, for example, the types itself have their definition of a discriminator.

To avoid any ambiguity, the suggestion is to remove `discriminator ` from any union type.

```yaml
PersonOrDog: 
   type: Person | Dog
   discriminator: hasTail # will be removed in RC2
```
