### ISSUE TITLE
Remove any support for inline declaration of JSON Schema or XSD in any type declaration

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#314]
The problem here is that having the ability to define inline JSON Schema or XSDs in any type declaration may introduce a lot ambiguity and creates very complex use cases when serializing it into something more specific. Therefore, we suggest to remove the support for inline declaration of both in any type declaration. One will still be able to define XSDs, JSON Schema, or types; but is not able to mix them.

**Comment by bademux** [comment]
why?
there are already format hel. Leave it as is or use yaml only, imho

**Comment by freddrake** [comment]
This sounds like excessive hand-holding, better addressed by a best practices document that can evolve independently and include rationale.

There are plenty of times highly localized types are appropriate; whether those should be pulled out or not will often be determined by human judgement.  No need to require one approach or another in the spec.

**Comment by sichvoge** [comment]
The biggest problem here is serialization of a specific type that mix up all three since not everything is interchangeable between these three formats. The questions that we would need to answer here are how these things are getting serialized into one specific which often is the case. How do you serialize it into XML after defining a type that mix all three?

It's something that we could not easily answer and therefore simplify the concepts for the type systems very first version. That does not mean we cannot evolve and bring these in when there is a better understanding how that will work, and how people use or want to use it.

**Comment by bademux** [comment]
@sichvoge  I'm not sure I fully understand the problem, can you please provide an example?

**Comment by sichvoge** [comment]
I only have a simple example that would illustrate what I mean by mixing types.

```yaml
  MixType:
    properties:
      JsonProperty:
        type: |
          {
            "title": "Example Schema",
            "type": "object",
            "properties": {
              "firstName": {
                "type": "string"
              },
              "lastName": {
                "type": "string"
              },
              "age": {
                "description": "Age in years",
                "type": "integer",
                "minimum": 0
              }
            },
            "required": ["firstName", "lastName"]
          }
      XmlProperty:
        type: |
          <xs:element name="item" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="note" type="xs:string" minOccurs="0"/>
                <xs:element name="quantity" type="xs:positiveInteger"/>
                <xs:element name="price" type="xs:decimal"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
      NormalType:
        properties:
          name: string
```

Now imagine more complex scenarios with XSD namespaces and different definitions. You also have multiple inheritance in JSON, but not in XSD. How do you basically serialize `MixType` into the different formats.
