### ISSUE TITLE
Define properties naming character set

### ISSUE THREAD

**Issue by fededonna** [raml-org/raml-spec#324]
we should define if any character is allowed as a name or we should only allow letters and numbers

for instance:

```yaml
types:
  Person:
    type: object
    properties:
      "name.first" : string
```

as per the code generation this will create a java class with the following structure which is invalid

```java
package org.raml;


public class Person {

    private String name.first;

    public String getName.first() {
        return this.name.first;
    }

    public void setName.first(String value) {
        this.name.first=value;
    }

}
```

or we should define the escaping convention for this type of names.
