### ISSUE TITLE
Add more clarification around the different default types and when they apply in which context

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#325]
The current RC1 version explains the different default types in section [Shortcuts and Syntactic Sugar](https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md#shortcuts-and-syntactic-sugar). In RC2 we should make sure that these are described a bit more clearly w/o using examples only.

There following rules need to be applied to determine the default type:

* If, and only if, a type declaration contains a `properties` node; the default type is `object`. For example (based on this rule):

```yaml
types:
   Person:
      type: object
      properties:
```

can also be written

```yaml
types:
   Person: 
      # default type is `object`, no need to explicitly define it
      properties:
```

* If, and only if, a type declaration does not contain either a `properties` node or no explicit `type`/`schema` node; the default type is always `string`. For example (based on this rule):

```yaml
types:
   Person:
      properties:
         name: # no type or schema necessary since the default type is `string`
```

* The default type `any` is applied to any `body` node regardless if it is a response or request declaration that does not contain `properties`, `types`, or `schema`. That rule is necessary since the value of a `body` node has the same structure like a type declaration except that the key is always a media type. For example:

```yaml
body:
  application/json: # key
    # default type is `any` 
```

The last rule is important for validation purposes and needs to be defined in the specification. Of course, each rule can be overridden by explicitly define a type. For example: 

```yaml
types:
   Person:
      properties:
         name: 
            type: number
```
