### ISSUE TITLE
Question about traits and default media types

### ISSUE THREAD

**Issue by svacas** [raml-org/raml-spec#326]
The example below defines a default media type and an explicit media type is defined by a trait:
```
#%RAML 1.0
title: default
mediaType: application/json

traits:
   foo:
     body:
       text/plain:
         example: pepe

/bar:
  post:
    is: foo
    body:
      example: "{}"
```
What is the expected output?

1. Error when trying to merge the trait body
2. Both media types are supported
3. The trait media type is used but with the example defined in the resource

I guess it's 1, what do you think?
