### ISSUE TITLE
Overriding inherited property of different types should not be allowed

### ISSUE THREAD

**Issue by fededonna** [raml-org/raml-spec#334]
```yaml
#%RAML 1.0 Library
types:
  Manager:
    type: Person
    properties:
      name: number
  Person:
    type: object
    properties:
      name:
        type: string
        maxLength: 10
```

As described in the type system this is allowed and the type of name under the manager object is number but I don't really know which restrictions apply to that. Despite of that property type change should not be allowed. Name is a string and should be a string in the manager object too.

**Comment by machaval** [comment]
Yes agree. This is why I hate inheritance and for me composition is much better.

**Comment by sichvoge** [comment]
This specific example is actually not allowed. Agreed and lets make that clear in the spec. the following though is allowed:

```
types:
  Manager:
    type: Person
    properties:
      name: string
  Person:
    type: object
    properties:
      name:
        type: string
        maxLength: 10
```

@fededonna right?
