### ISSUE TITLE
Create a dictionary Type which is using custom Types already defined

### ISSUE THREAD

**Issue by vayias** [raml-org/raml-spec#369]
So let's say I have TypeA which is a string and TypeB which is an object. 

I want to define Type3 which is a dictionary with key TypeA and value TypeB. It's not clear how to do that in the documentation.

**Comment by sashabaranov** [comment]
@sichvoge +1, I also need this

**Comment by sashabaranov** [comment]
The best I came up with:

```yaml
  Value:
    properties: 
      name: TypeA
      value: TypeB
  Type3:
    type: Value[]
```
