### ISSUE TITLE
Add support for multiple examples

### ISSUE THREAD

**Issue by dkirrane** [raml-org/raml-spec#37]
Currently, one can only add a single example json. It would be a nice enhancement to allow multiple examples like this:

```
      body:
        application/json:
          example: !include example1.json
          example: !include example2.json
```
