### ISSUE TITLE
Clarify array types to be a valid definition for `type`

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#370]
Currently the spec does not clearly states that `array` is a valid value for a `type` node. Its basically just stating that one can define an array type by using the array qualifier at the end of a type expression.

So following are both valid examples:

```yaml
types:
  Email:
    type: object
    properties:
      name:
        type: string
  emails:
    type: Email[]
    minItems: 1
    uniqueItems: true
```

```yaml
types:
  Email:
    type: object
    properties:
      name:
        type: string
  emails:
    type: array
    items: Email
    minItems: 1
    uniqueItems: true 
```

Using `Email[]` is equivalent to use `type: array` and specifically define the type items in the array inherit from using `items` facet.
