### ISSUE TITLE
Expand the example when an instance of a union type is valid.

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#397]
Currently, we have a small example that explains when an instance of a union type is valid. We can expand that to make more clear what that actually means in a more complex scenario. 

-------------

A valid instance of a union type must pass all restrictions associated with at least one of the union type options. For example:

```yaml
types:
  CatOrDog:
    type: Cat | Dog # options: Cat or Dog
  Cat:
    type: object
    properties:
      name: string
      color: string
  Dog:
    type: object
    properties:
      name: string
      fangs: string
```

A valid instance of the type CatOrDog for example looks like the following:

```yaml
CatOrDog: # follows restrictions applied to the type 'Cat'
  name: "Musia",
  color: "brown"
```

Imagine a more complex example where a union type is used in a multiple inheritance case.

```raml
types:
   HomeAnimal: [ HasHome ,  Dog | Cat ]
```

In this case type `HomeAnimal` has two base types `HasHome` and anonymous union type defined by a type expression - `Dog | Cat`  

So testing if the `HomeAnimal` type is a valid involves  taking each of its base types, and checking that a type which is derived type of this type and each of union type option types is a valid type. In this particular case you need to test that types `[HasHome, Dog]` and `[HasHome, Cat]` are valid types.

If you are extending from two union types you should do the same for every possible combination for example in this case:

```raml
types:
   HomeAnimal: [ HasHome | IsOnFarm ,  Dog | Cat | Parrot ]
```

In summary, you need to test 6 possible combinations: `[HasHome, Dog ]`, `[HasHome, Cat ]`, `[HasHome, Parrot]`, `[IsOnFarm, Dog ]`, `[IsOnFarm, Cat ]`, and `[IsOnFarm, Parrot]`.
