### ISSUE TITLE
 Re-work 'Multiple Inheritance' chapter.

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#407]
In RC1, multiple inheritance was restricted to object types only. That is not the case in RC2 anymore as long as the resulting type is a fully valid type.

The following example is valid:

```yaml
types:
   Number1:
     type: number
     minimum: 4
   Number2:
     type: number
     maximum: 10
   Number3: [ Number1, Number2]
```

Where as using the same example and only change the maximum value of type `Number2` from 10 to 2 would result into an invalid type `Number3`.

```yaml
types:
   Number1:
     type: number
     minimum: 4
   Number2:
     type: number
     maximum: 2
   Number3: [ Number1, Number2]
```
