### ISSUE TITLE
URIs in security schema description can be parameter dependent.

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-spec#45]
With Magento and Jira we have faced the following problem:

URIs in security schemas are defined as relative to domain.
For example, in Megento we have:

``` yaml
baseUri: "{protocol}://{domain}/api/rest"
securitySchemes:
  - oauth_1_0:
    type: OAuth 1.0
    settings: 
      requestTokenUri: "{protocol}://{domain}/oauth/initiate"
      authorizationUri: "{protocol}://{domain}/oauth/oauth_authorize"
      tokenCredentialsUri: "{protocol}://{domain}/oauth/token"
```

http://www.magentocommerce.com/api/rest/authentication/oauth_authentication.html

We noticed notebooks not to support such definition and refered to the RAML spec. The spec does not make it clear how to describe security schemas with variable URIs.
