### ISSUE TITLE
Add "requires" parameter validation

### ISSUE THREAD

**Issue by blakeembrey** [raml-org/raml-spec#46]
Adding an new "requires" validation parameter could be useful when validation queries. I would like to suggest the syntax `requires: path` for specifying that a parameter requires another for use. For example:

``` yaml
queryParameters:
  lat:
    type: string
    requires: lng
  lng:
    type: string
    requires: lat
```
