### ISSUE TITLE
Add UUID parameter type

### ISSUE THREAD

**Issue by vanDonselaar** [raml-org/raml-spec#483]
We're using UUID's rather than Integers in our API to identify entities. It would be nice to have a `uuid` parameter type rather than using `string` for UUID's.

**Comment by fededonna** [comment]
@vanDonselaar why not use a string with a regex and define your own type?

**Comment by vanDonselaar** [comment]
How can I 'define my own type' exactly? Sounds interesting!

When using the `raml-for-jax-rs` generator (or any other generator), the generator can decide to generate a `java.util.UUID`(or `System.Guid` in .NET) instead of a String which you'll have to cast to a UUID. After all, a UUID is a very well-defined type with a proper RFC. Regexes are nice, but by your reasoning we could also decide to remove the Integer type by replacing it with a string and a regex like `^[0-9]*$`. :wink:

**Comment by sichvoge** [comment]
Thats simple using the data type language introduced in RAML 1.0. For example:

```yaml
types:
   UUID:
      type: string
      pattern: ^[0-9]*
```

**Comment by fededonna** [comment]
Yes, you can change integer for whatever you want, but that's not this case. You are trying to validate a string. you can define your type as follows

``` yaml
types:
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
```

and please don't cast, try using something as tryParse, your code will look much nicer.
