### ISSUE TITLE
Referencing declared schemas?

### ISSUE THREAD

**Issue by idris** [raml-org/raml-spec#5]
The spec provides a way to [define named schemas](https://github.com/raml-org/raml-spec/blob/master/04_basic_information.md#schemas), but in "Schemas and Responses", it doesn't explain how to reference a schema defined in the root. It only shows how to do define the schema inline, or via an include.

If I define schemas at the root, like:

``` yaml
schemas:
  User:  schema/user.json
  Users: schema/users.json
  Org:   schema/org.json
  Orgs:  schema/orgs.json
```

Then I'd expect to be able to use that schema in a response definition like:

``` yaml
/users/{userId}:
  get:
    body:
      application/json:
        schema: User
```
