### ISSUE TITLE
[RAML 1.0] Using external type as array in DataType

### ISSUE THREAD

**Issue by codercms** [raml-org/raml-spec#509]
Hey, i have Type1 and Type2.
So i want to use Type2 in Type1 as array, but i can't find a way to do this.
```
#%RAML 1.0 DataType
type: object
displayName: Type1
properties:
  id:
    type: !include Type2.raml


#%RAML 1.0 DataType
type: object
displayName: Type2
properties:
  id:
    type: integer
```

I tried this:
```
uses: 
  types:
    Type2: !include Type2.raml
```

But it doesn't work.
How can i use external type as array in another type?
