### ISSUE TITLE
Resolution of resource type parameters using libraries

### ISSUE THREAD

**Issue by svacas** [raml-org/raml-spec#510]
The following raml has types with the same name in the root raml and the dependent libraries that is passed as a resource type parameter. 
Which would be the final types of headers hA, hA2, hB, hB2?

```raml
#%RAML 1.0
title: type shadows
uses:
    a: libA.raml

types:
    Monkey: string

/users:
    type:
        a.rtA:
            kind: Monkey    
```
```raml
#%RAML 1.0 Library
# libA.raml

uses:
    b: libB.raml

types:
    Monkey: number

resourceTypes:    
    rtA:
        type: 
            b.rtB:
                kindB: <<kind>>
        post:
            headers:
                hA: <<kind>>
                hA2: Monkey
```
```raml
#%RAML 1.0 Library
# libB.raml

types:
    Monkey: boolean

resourceTypes:    
    rtB:
        post:
            headers:
                hB: <<kindB>>
                hB2: Monkey
```

**Comment by petrochenko-pavel-a** [comment]
It is definitely not clarified in the spec at this moment. As well as I know current JS parser implementation, tracks parameter origin and initially attempts to resolve type from parameter origin, if it is failed it attempts to resolve locally defined type with a given name.

So in your example:

`hA` - type from `api.raml`, `hA2` - type from `libA.raml`, `hB` - type from `libA.raml`, `hB2` - type from `api.raml`

Regards,
Pavel

**Comment by svacas** [comment]
Looks a bit counter-intuitive to treat a parameter that resolves to value `X` different than the literal value `X`. What will happen when you mix things?

e.g.: `type: suffix-<<param>>`

I'm not able to figure out an elegant way to resolve this, but whatever decision is taken needs to be clarified in the spec.

**Comment by sichvoge** [comment]
Don't forget to create a PR with that clarification ;)

**Comment by svacas** [comment]
after discussing with several raml users we arrived to the following proposal:

references are resolved first in the context where they were defined and if not present there they are looked up in the parent context. Contexts are defined for root raml files and typed fragments (e.g.: libraries, data types, resource types, etc.).

In the example provided before the resulting type of the headers would be:
```
hA:  number  (from libA)
hA2: number  (from libA)
hB:  boolean (from libB)
hB2: boolean (from libB)
```

**Comment by ddenisenko** [comment]
The issue with the latest proposed approach is that in such a case user will have to closely investigate the code of the resource type / trait in order to use it.

By passing `Monkey` as a parameter in `api.raml` user definitely wanted to the string one, because no other `Monkey` is available in that context under `Monkey` name. 

User could have no idea that there is another `Monkey` defined in the library, there can be a thousand lines between `rtA ` resource type and `Monkey` definition in the `libA.raml` code. 

As a result user can be greatly confused and spend a lot of time to find another `Monkey`, which is causing API to behave differently from user's expectations.

I vote for Pavel's variant.

**Comment by ddenisenko** [comment]
@usarid , @sichvoge what are your thoughts?

**Comment by machaval** [comment]
@ddenisenko And what about the other Santiago's scenario ```type: suffix-<<param>>```. 
Is this suppose to be resolved in the param context or in the library.

**Comment by ddenisenko** [comment]
I edited my original proposal to make it clear that we do not replace Monkey type with string/number/boolean. string/number/boolean was listed just to clarify, which Monkey we take in each case.

So, the proposal looks like this:

hA:   Monkey (`type: string` from `api.raml`)
hA2: Monkey (`type: number` from `libA.raml`)
hB:   Monkey (`type: string` from `api.raml`)
hB2: Monkey (`type: boolean` from `libB.raml`)

**Comment by ddenisenko** [comment]
Regarding the prefixes/suffixes.

We perform the textual substitution first, resolving second.

So in case of the following RAML:

api.raml:
```
title: type shadows
uses:
    a: libA.raml

types:
    Monkey: string

/users:
    type:
        a.rtA:
            kind: onkey  
```

```
#%RAML 1.0 Library
# libA.raml

types:
    Monkey: number

resourceTypes:    
    rtA:
        post:
            headers:
                hA: M<<kind>>
                hA2: Monkey
```

We will still have:
hA:   Monkey (`type: string` from `api.raml`)
hA2: Monkey (`type: number` from `libA.raml`)

**Comment by machaval** [comment]
This I don't get it because we can get more creative and ```hA2``` key be a parameter. 
```<<keyName>> : Monkey``` Is this still resolved to libA.raml? Also what happen if it has more than one parameter from different sources? There can be a lot of use cases here and people can get really creative.

**Comment by ddenisenko** [comment]
Yes, hA2 key can be a parameter. This is not a problem for both approaches, and should be supported by both too. 

Basically, both approaches do perform textual substitution and both approaches must understand the semantics (like recognizing type references), because both finally should be printing the JSON, where each type and other references must be prefixed by the proper namespace.

In example, for the approach proposed by Santiago and I would expect the final expanded RAML look effectively the following:

```
#%RAML 1.0
title: type shadows
uses:
    a: libA.raml
    b: libB.raml

types:
    Monkey: string

/users:
  post:
    headers:
        hA: a.Monkey
        hA2: a.Monkey
        hB: b.Monkey
        hB2: b.Monkey
```

I omitted `type` for simplicity. Import (uses instruction) of `libB.raml` must be performed automatically.
So, again, to provide the final result both approaches should understand that type reference is type reference etc.


There are more interesting cases, where the approach I proposed (and Pavel actually also meant it) is certainly more complex to implement.

In example:

```
#%RAML 1.0
title: type shadows
uses:
    a: libA.raml

types:
    Monkey:
        properties:
              propA: string

/users:
    type:
        a.rtA:
            param1: Monkey
```

```    
#%RAML 1.0 Library
# libA.raml

uses:
    b: libB.raml

types:
    Monkey:
        properties:
              propB: number

resourceTypes:    
    rtA:
        type: 
            b.rtB:
                param1: <<param1>>
                param2: Monkey
```

```
#%RAML 1.0 Library
# libB.raml

types:
    Monkey:
        properties:
              propC: boolean

resourceTypes:    
    rtB:
        post:
            headers:
                hB: <<param1>> | <<param2>> | Monkey
```

In this case, the expanded RAML should look like:

```
#%RAML 1.0
title: type shadows
uses:
    a: libA.raml
    b: libB.raml

types:
    Monkey: string

/users:
  post:
    headers:
        hB: Monkey | a.Monkey | b.Monkey
        
```

So both approaches are handling "static" parts in the same way. Both approaches have to recognize references and perform the proper automatic imports (if needed) and assign the proper namespaces in the expanded RAML.

The key difference between the approaches is the the one I propose makes parser to track parameters and their sources, and resolves the names -only for parameters- starting from the scope, parameter value was defined in and ending in the scope, the resource type/trait is defined in.

And yes, I agree that users can be quite creative, in example:
`type: Prefix<<param1>>And<<param2>>Suffix`
This one does not contradict to both approaches, but is weird from any point of view.

**Comment by sichvoge** [comment]
Finally I had a chance to read through the different comments and the two suggested options from @svacas and @ddenisenko. In my opinion, the second option from Denis looks like the best approach from a users perspective. The reason being, using a library does actually not mean that I know everything about it. The only thing that I definitely know is what the available resource types are and if one defines a parameter, that I have to provide it. All in my known context. So, in Denis example:

```yaml
#%RAML 1.0
title: type shadows
uses:
    a: libA.raml

types:
    Monkey: string

/users:
    type:
        a.rtA:
            kind: Monkey 
```

The only visible information I have is that the provided `Monkey` kind is the one that I have defined in my context. I don't know that there is another inside the library and I might not really care about that. My expectations are that the processor picks the one that I have defined and not the one that is hidden inside the library. Obviously there are many really really strange corner cases where people can get very creative, but my decision would always be that the processor looks inside the local context where I have used the resource type first and if there is nothing go to the context where the resource type has been defined narrowing down the information that needs to be placed instead of the parameter. With Santiago's approach, and Denis is correct, the consumer would need to learn everything about the library and its content before he/she can start using it. That's not always the expectations. I just want to use it and define things that are visible for me. Again, there are many very weird corner cases like the one with the prefix and suffix which is difficult to handle indeed. Let's assume you have:

```yaml
#%RAML 1.0
title: type shadows
uses:
    a: libA.raml

types:
    Monkey: string

/users:
    type:
        a.rtA:
            kind: Monkey
```

```yaml
#%RAML 1.0 Library
# libA.raml

types:
    post-Monkey: number

resourceTypes:    
    rtA:
        post:
            headers:
                hA: post-<<kind>>
                hA2: Monkey
```

What would the consumer expect? Obviously he would expect you to resolve the type into `Monkey` since that is the context I work in, but it actually resolves into `post-Monkey`. That can get really confusing for the end consumer of the resource type `rtA` since he/she does not know there is a suffix. So how can you make sure to help the consumer to understand that the parameter is suffixed with `post-` and might not get resolved to what you would expect? But these are corner cases and more definition problems that might need to be clarified / fixed  and documented during the design phase. 

All in all, my vote goes to @ddenisenko option as it seems the correct one from a consumer expectation perspective.

**Comment by svacas** [comment]
I'll try to summarize your approach to check if we are on the same page:

- references from explicit parameters are resolved in the context where the value is assigned, and if not present there in the context of the resource type/trait.

- literal references are resolved in the context were defined and cannot be overridden by the context where the resource type/trait is used.

Points to discuss:

- I guess implicit parameters (resourcePathName, methodName) are first resolved in the context where the resource type/trait is used, like the explicit ones.

- we need to define what to do with mixed references composed of parameters from different contexts and literal values (extreme case, but needs to be addressed)

- Denis and Christian approach is different regarding the propagation of the type through the resource type inheritance chain. In Denis' case if the value assigned to a parameter X comes from a previous parameter Y then Y context is used, which may be the expected outcome.

**Comment by ddenisenko** [comment]
> references from explicit parameters are resolved in the context where the value is assigned, and if not present there in the context of the resource type/trait.

Yes. If the value is absent in the value assignment context, we can fall back either to the next context in the chain between value assignment context and particular resource type / trait context, or right to the resource type / trait context itself. Doesn't matter much as this case is probably the rare one.

>literal references are resolved in the context were defined and cannot be overridden by the context where the resource type/trait is used.

Yes.

All in all, lets wait for decision regarding the general approach, then discuss the details.

**Comment by ugorji** [comment]
Hi, 

Is there any update on this? Libraries are pretty tough to use if the library has to know about the types defined in the RAML in which it is being called. I understand that there are some subtle use cases, some of which are listed here e.g. where both the library user and the library define similarly named types. However, the more general case where the type is only defined in the library user should be supported.

In my use case (as attached), it's failing validation using both the javascript and java parsers. Unfortunately, I can't really grok anything from the error messages, which are very different from the java and javascript parsers. I'm attaching the raml zip, and log files containing the error output of the java and javascript parsers, and how I ran the parsers.

It will be nice if this is resolved in the spec, and parsers, before Mule 3.8.1 is released.

[customer.raml.zip](https://github.com/raml-org/raml-spec/files/340448/customer.raml.zip)
[customer.raml.error.cmdline.txt](https://github.com/raml-org/raml-spec/files/340450/customer.raml.error.cmdline.txt)
[customer.raml.error.java.txt](https://github.com/raml-org/raml-spec/files/340451/customer.raml.error.java.txt)
[customer.raml.error.javascript.txt](https://github.com/raml-org/raml-spec/files/340452/customer.raml.error.javascript.txt)

Thanks.

@usarid

**Comment by sichvoge** [comment]
After talking to @usarid and one other independent "source" ( @antoniogarrote ) who is very experienced with languages as well to get a different perspective. He creating a [Lisp program](https://gist.github.com/antoniogarrote/ed5e92e8b5a73b8a5ce3224ac768d82d) (that supports macros) that shows how the expansion should work in his opinion.

His conclusion aligns to @ddenisenko results, and I asked him to give us more details here coming today.

Looking at the different approaches and exercises @ddenisenko approach is the strongest as not only him, but also Antonio and Uri came to the same conclusion. IMHO, we should move forward with that as a base and start to discuss the different corner cases and close gaps / interpretation to get to a formal algorithm that describes the resolution which we can put into the specification.

I'd like to discuss the following questions:

1) We haven’t really defined what a parameter actually takes. Is it a literal, a references or an object?
2) What if we define a trait and a type with the same key name?
3) What if the type is object and we want to provide a literal which might have the same value vs a type key name (eg “Monkey” vs Monkey)? 
4) What if the type is object, how do we handle `post-<<param>>` or `hello<<param>>world`? Are we saying that in these cases a param is a string by default?
5)  What about functions, for example: `<<param | !singularize>>`? Handling params as string again?

------------------------

That is the result from a quick 1:1 chat with Denis.

> 1) We haven’t really defined what a parameter actually takes. Is it a literal, a references or an object?

Parameter is always a string. The string can be later treated as a reference, or not, depending on where exactly that string is applied, how it is looking according to its surroundings (in example, two parameters concatenated together) etc. But, there is also a "source of the value" associated with the parameter application, so if its application appears to be a reference, we can later use that to resolve the reference.

In other words, there are **two** phases here.

### Phase 1

Treat parameters as pure strings and do not care of the values at all except remembering the source. 

@ddenisenko compared to @antoniogarrote you basically set scopes right? (looking at the gist he added a symbol in front of each value of the relevant nodes which basically represents the scope)

### Phase 2

At the second phase, we check all the places where references can be. ​*If the reference is found, we resolve it and patch the string if needed. And that happens whether there was a parameter value in that string or not*​, the only difference is the way we juggle with the reference resolving context.

### Example

```yaml
#%RAML 1.0
# api.raml 

title: type shadows
uses:
    a: libA.raml

types:
    Monkey: string

/users:
    type:
        a.rtA:
            kind: Monkey
```

```yaml
#%RAML 1.0 Library
# libA.raml

types:
    MonkeyA: number

resourceTypes:    
    rtA:
        post:
            headers:
                hA: <<kind>>
                hA2: Monkey2
```

```yaml

After phase 1:

```yaml
#%RAML 1.0
title: type shadows
uses:
    a: libA.raml

types:
    Monkey: string

/users:
  post:
    headers:
        hA: Monkey      #We remember that the source of this one is root.raml, so we dont need to patch this to suite well in root.raml
        hA2: Monkey2    #We remember that the source of this one is libA.raml, so we need to patch this to a.Monkey2 to suite in root.raml
```

After phase 2 (end result):

```yaml
#%RAML 1.0
title: type shadows
uses:
    a: libA.raml

types:
    Monkey: string

/users:
  post:
    headers:
        hA: Monkey
        hA2: a.Monkey2
```

Notice that we analyze both `hA` and `hA2` just because both are potential references. Then we resolve both and make a decision of whether to patch the value for it to be a valid reference in the context of root.raml to what we actually want to reference.

During that patching we do not change `hA: Monkey` as its already a correct reference in the context of root.raml that points to Monkey type from root.raml. But we need to patch `hA2: Monkey2` to become `hA2: a.Monkey2`, even though it is not related to parameters at all, for it in the context of root.raml to correctly point to Monkey2 type in libA.raml. And at this point we could be also automatically generating an import of libA.raml if it is absent.

> 2) What if we define a trait and a type with the same key name?

We dont care. Everything are strings at the first phase. At the second phase we known whether this reference points to the trait or a type due to knowing the language structure.

> 3) What if the type is object and we want to provide a literal which might have the same value vs a type key name (eg “Monkey” vs Monkey)?

If you your string "Monkey" goes to a description, we do not resolve and patch it.

If your string "Monkey" goes to `type: <<MonkeyTypeHere>>` or `is: <<MonkeyTraitHere>>`, we will resolve and patch it.

> 4) What if the type is object, how do we handle `post-<<param>>` or `hello<<param>>world`? Are we saying that in these cases a param is a string by default?

That is a very good question.

At the first phase its all simple and clear:

`type: HereWillBeThe<<param>>` with `param==Monkey` becomes `type: HereWillBeTheMonkey`,
`type: <<param1>>WillBeThe<<param2>>` with `param1==Here,param2==Monkey` becomes `type: HereWillBeTheMonkey`,


​*And we need to decide what to do on the second phase.*​

We have two options:

1. As soon as the reference value is not completely filled with parameter, we just ignore the fact that the parameter was used here at all. This does not mean this reference will never be patched. It just means, we do not start calculating where the reference points to from the context, parameter value comes from, but instead we start calculation from this current context.

2. Establish a more complicated rule, like if we have the following context chain : [root.raml] <- [Unit, where param1 value is set] <- [Some other unit] <- [Unit, where param2 value is set] <- [Current library unit with `type: <<param1>>WillBeThe<<param2>>` inside], we calculate the unit, which was used as a source of some parameter value and is closest to the expansion root (root.raml), and that will be [Unit, where param1 value is set], and use its context to start resolving `HereWillBeTheMonkey` type. If we cant find type `HereWillBeTheMonkey` in that unit, we than proceed to  [Some other unit] , and then all the way to [Current library unit with `type: <<param1>>WillBeThe<<param2>>` inside] in the end.

I do not know, which approach is better. But I should mention that while this one looks a bit artificial, and it is not very important of how we trait this kind of cases, there is also a case, where we will have to break out own rules of treating everything as strings and then resolving references as a whole, and these are type expressions:

​*Here is the exceptional case*​:

Imagine `type: <<param1>> | <<param2>>`. In this case we still first work on pure strings level: `type: FirstType | SecondType`. But then we are not resolving `FirstType | SecondType` as a whole, instead we resolve `FirstType` and `SecondType` separately, and start resolving each one in its own context: where `FirstType` value comes from and where `SecondType` value comes from.

> 5) What about functions, for example: `<<param | !singularize>>`? Handling params as string again?

Functions are resolved during the first "string" phase.

---------------------

Feedback?
