### ISSUE TITLE
Example for using arrays in URI parameters is wrong

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#512]
The example on how to serialize arrays in URI parameters is wrong https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#template-uris-and-uri-parameters

```yaml
#%RAML 1.0
title: Serialization API

/users:
  description: All users
  /{userIds}:
   description: A specific user
   uriParameters:
     userIds:
       description: A list of userIds
       type: array
       items:
         type: string
         minLength: 1
         uniqueItems: true # wrong indent
```

should be

```yaml
#%RAML 1.0
title: Serialization API

/users:
  description: All users
  /{userIds}:
   description: A specific user
   uriParameters:
     userIds:
       description: A list of userIds
       type: array
       items:
         type: string
         minLength: 1
       uniqueItems: true # correct
```
