### ISSUE TITLE
Null type should be enclosed with quotes when used alone

### ISSUE THREAD

**Issue by svacas** [raml-org/raml-spec#514]
The example below from the spec doesn't look right, as both property types are `null` and so default to `string`.
```
types:
  NullValue:
    type: object
    properties:
      name:
      comment: null
    example:
      name: Fred
      comment: # Providing a value here is not allowed.
```
From the yaml spec all the following values resolve to null:
```
type1: 
type2: null
type3: Null
type4: NULL
type5: ~
type6: !!null
```
So when `null` is not used as part of a bigger type expression (in which case is coerced to string automatically) it should be entered as `"null"`.
