### ISSUE TITLE
Is OAuth 1.1 really indicated with `oauth_1_0.raml`?

### ISSUE THREAD

**Issue by chasm** [raml-org/raml-spec#516]
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#default-security

**Comment by sichvoge** [comment]
Hi @chasm, its not. The `oauth_1_0.raml` is only a file that contains the actual definition of your OAuth 1.0 scheme. For example, the following could be the content of this file:

```yaml
description:|
  OAuth 1.0 continues to be supported for all API requests, but OAuth 2.0 is now preferred.
type: OAuth 1.0
settings:
  requestTokenUri: https://api.mysampleapi.com/1/oauth/request_token
  authorizationUri: https://api.mysampleapi.com/1/oauth/authorize
  tokenCredentialsUri: https://api.mysampleapi.com/1/oauth/access_token
  signatures: [ 'HMAC-SHA1', 'PLAINTEXT' ]
``` 

Everything explained in [here](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#security-schemes). Hope that is helpful, let me know if there is more.
