### ISSUE TITLE
Type declaration in response body with default media types

### ISSUE THREAD

**Issue by dustinmoris** [raml-org/raml-spec#517]
Hi, I can't seem to get this working.

I have the following default media type at the top of my document:
`mediaType: [ application/json, application/xml ]`

Then I have a custom type declared:
```
types:
  MyType:
    type: object
    properties:
      status: string
      message: string
```

Now I would like to specify that the response object of an API call will be of that type:

```
responses:
      200:
        body:
          type: MyType
```

but unfortunately this doesn't seem to get parsed as valid RAML. It seems like I have to place the media type in between the body and type declaration, but that defeats the whole purpose of the default media type at the top. What am I doing wrong?
