### ISSUE TITLE
the example for query string still uses rc1 syntax

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#520]
The example for query string that uses multiple inheritance and union type still uses RAML 1.0 RC1 syntax for examples (`content`:RC1 vs `value`:GA)

The example should be the following:

```yaml
#%RAML 1.0
title: Illustrate query parameter variations
types:
  lat-long: # lat & long required; mutually exclusive with location
    properties:
      lat: number
      long: number
  loc: # location required; mutually exclusive with lat & long
    properties:
      location:
  paging: # each is optional, not exclusive with anything
    properties:
      start?: number
      page-size?: number
/locations:
  get:
    queryString:
      type: [paging,  lat-long | loc ]
      examples:
        first:
          start: 2
          lat: 12
          long: 13
        second:
          start: 2
          page-size: 20
          location: 1,2
        third:  # not valid
          value:
            lat: 12
            location: 2
          strict: false # because it's not valid
```
