### ISSUE TITLE
Define Repeat scalar valued node usage

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-spec#534]
In the list of available scalar-valued nodes Repeat is listed but is not defined the usage

https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#annotating-scalar-valued-nodes

Example:

```yaml
#%RAML 1.0
title: My API With Types
types:
  Initial_comments:
    type: object
    minProperties: 2
    maxProperties: 4
    properties:
      comment_id?: number
      initial_comments?:
        type: string
        repeat: true

```
