### ISSUE TITLE
RAML 1.0 Arrays: inside an object or plain array?

### ISSUE THREAD

**Issue by thevangelist** [raml-org/raml-spec#537]
Here's what RAML 1.0 says about arrays: https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#array-type

However the specifications isn't exactly clear whether to use a Array... Assuming I have a of `body: Pokemons[]`, should I use an array like this in my JSON, where each Pokemon is:

``` 
type: object
description: Pokemon
properties:
  name:
    type: string
    description: Pokemon name
  description:
    type: string
    description: Description of Pokemon
``` 

A)
```
{
	"pokemons": [{
		"name": "Pikachu",
		"description": "Electric"
	}, {
		"name": "Bulbasaur",
		"description": "Dual-type Grass/Poison"
	}]
}
```

or B)

```
[{
	"name": "Pikachu",
	"description": "Electric"
}, {
	"name": "Bulbasaur",
	"description": "Dual-type Grass/Poison"
}]
```

Both are valid json according to: http://jsonlint.com/

**Comment by sichvoge** [comment]
Really depends. I would say its mostly A) since you always use a key-value pair in YAML. In your example you would have:

```yaml
types:
  Pokemon:
  PokemonGo:
    properties:
      pokemons: Pokemon[]
```

The only place where B) can be relevant is if you have something like:

```yaml
types:
  Pokemon:
  Pokemons: Pokemon[]
```

**Comment by thevangelist** [comment]
Hmm, shouldn't the specification be unambiguous? Say there's two companies implementing equivalents on each side and if the spec isn't unambiguous, both sides can implement it differently?

**Comment by sichvoge** [comment]
Its unambiguous as far as you can get with plain English. The actual output just depends if you say a type is an array or a property. Same in JSON schema.

**Comment by freddrake** [comment]
For ``body: Pokemon[]``, I'd expect B only.

jsonlint.com is irrelevant here; both examples are JSON, but only B conforms with ``body: Pokemon[]``.

**Comment by sichvoge** [comment]
@freddrake so you think we have to clarify anything in the specification? if yes, there are multiple places but maybe we should provide an additional reference document that explains how RAML data types do map into JSON schema?

**Comment by freddrake** [comment]
@sichvoge I think the specification is clear. If more examples are required (indicated by questions like this coming up), an informative document can be added.  My interpretation is based on interpreting what's in the spec, without bringing in outside expectations based on what I'd like to see in an actual API.

(I think it's clear that my expectation of RAML is that I can use it to describe an API accurately and unambiguously, even if that API doesn't conform to best practices. Because humans have a hard time agreeing on the later. Best practices considerations are best left to linters.)

**Comment by sichvoge** [comment]
OK. I think an informative document makes some sense especially around mapping into JSON schema. If one would like to start with that, go for it :) Otherwise, it would take me some time to consolidate something

**Comment by stevenroose** [comment]
I think this is cleared out, and can be closed.

If anyone has a spare minute, quick question: is it possible to define arrays of objects inline without creating a global type?
Something like
```raml
[...]
application/json:
  type: object[]
  properties:
    name: string
    age: integer
  example: |
    [
      {
        "name": "harry",
        "age": 18
      }
    ]
```

**Comment by sichvoge** [comment]
Hi, you should be able to do this without using type expressions (`[]`). In your case, the following works:

```yaml
[...]
application/json:
  type: array
  items:
    type: object
    properties:
      name: string
      age: integer
    example: |
      [
        {
          "name": "harry",
          "age": 18
        }
      ]
```
