### ISSUE TITLE
Is not defined if displayName should be changed or not by an Overlay 

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-spec#538]
In the following example, display name is changed:

```yaml
#%RAML 1.0
title: hybrid-rest-services
version: 0.4
mediaType: application/json
securedBy: x-ttt
protocols: HTTP
securitySchemes:
   x-ttt:
      type: Digest Authentication

baseUri: https://anypoint.mulesoft.com/hybrid/api/v1
traits:
   env-org-pair:
      displayName: masterDisplayName
resourceTypes:
   servers-collection:
/servers:
  is: env-org-pair
  securedBy: x-ttt

```

```yaml
#%RAML 1.0 Overlay
title: Extension
extends: api.raml
traits:
  env-org-pair:
      displayName: overlayDisplayName

```

ISSUE: 
Spec does not define if displayName should be changed or not by an overlay
And if it is a behaviour change or not depends on the interpretation

Need clarification on if displayName should be affected or not by an overlay

https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#overlays
