### ISSUE TITLE
Nesting traits into resource types with resourcePathName parameters

### ISSUE THREAD

**Issue by zsim0n** [raml-org/raml-spec#560]
Hello

 I am trying to build the following construct:
```yaml 
collection.raml
#%RAML 1.0 ResourceType
description: A collection of <<resourcePathName|!uppercamelcase>>
get:
  description: |
    Get all <<resourcePathName|!uppercamelcase>>,
    optionally filtered
  is: [ hasResponseCollection ]
```
```yaml 
hasResponseCollection.raml
#%RAML 1.0 Trait
usage: Use this trait for resources whose response body is a collection of items
responses:
    200:
      body:
        application/json:
          type: <<resourcePathName|!singularize|!uppercamelcase>>[]
```
and of course the api.raml
``` yaml
api.raml
...
types:
  Examples: !include types/examples.raml
ResourceTypes:
    collection: !include resourceTypes/collection.raml
traits:
  hasResponseCollection: !include traits/hasResponseCollection.raml
...
/example:
  type: collection
```
But than neither the [api workbench](http://apiworkbench.com) and [anypoint](https://anypoint.mulesoft.com) api designer cannot resolve the `resourcePathName`parameter in the trait. 

I've tried transport the `resourcePathName`parameter via an custom parameter like this:
`[ hasResponseCollection : {typeName:  <<resourcePathName|!singularize|!uppercamelcase>>}]` without success.

Is this a valid construct? How should I do this in a better way?
Thanks
Zoltan

**Comment by sichvoge** [comment]
Hi @zsim0n,

You are actually not doing anything wrong, really. Since it seems a bug inside the parser, I raised an issue on that repo. You can follow the process with the link above this comment.  

Nevertheless, you might get design time problems with the resource type fragment validation since it defines an unknown trait. A workaround would be to use libraries. Libraries give you a centralized place to define a bundle of reusable assets that you can use where ever you want. Even in other typed fragments. See an example below. Unfortunately, the issue still exists ;)

```yaml
# collection.raml
#%RAML 1.0 ResourceType

uses:
  lib: library.raml

description: A collection of <<resourcePathName|!uppercamelcase>>
get:
  description: |
    Get all <<resourcePathName|!uppercamelcase>>,
    optionally filtered
  is: [ lib.hasResponseCollection ]
```

```yaml
# library.raml
#%RAML 1.0 Library

resourceTypes:
  collection: !include collection.raml
traits:
  hasResponseCollection: !include hasResponseCollection.raml
```
