### ISSUE TITLE
post application/json by type

### ISSUE THREAD

**Issue by EagleMoor** [raml-org/raml-spec#564]
Hi. How use type for post application/json as body? In all example i see just json schema. It's not a cool, write type & write schema for one object.

**Comment by sichvoge** [comment]
There are a couple of examples in the spec, but there is nothing fancy you need to do on your side:

```yaml
# anonymous type
application/json:
  type: object
  properties: 
    ...
```

or referring to an existing type:

```yaml
application/json:
  type: Dog
```
