### ISSUE TITLE
How can i apply an empty object or array in example?

### ISSUE THREAD

**Issue by e-cloud** [raml-org/raml-spec#567]
i can't find a way to use empty object or array in the example

**Comment by sichvoge** [comment]
an empty object really depends if you declared an instance to allow the miss of the value (see `nil` type), and for the example and array; use the YAML syntax for defining arrays. for example:

```yaml
example:
  arrayProperty:
    - 
      prop1:
      prop2:
    - 
      prop1:
      prop2:
```
