### ISSUE TITLE
How can i define a fixed value of a property of an inherited type?

### ISSUE THREAD

**Issue by e-cloud** [raml-org/raml-spec#568]
One common case of OO design, a `subclass` of the `superclass` may have a fixed value of a property defined in the `superclass`.

For example, a tree data structure represented by an array of nodes. Obviously it could have various types of node.

```yaml
types:
  NodeType:
    enum:
      - a
      - b
      - c

  treeNode:
    type: object
    properties:
      id:
      pid:
      type:
        type: NodeType

  aNode:
    type: treeNode
    properties:
      type: # i want a fixed value like `a` here
```

i came up with two approach:
* use default value
```yaml
...
  aNode:
    type: treeNode
    properties:
      type:
        default: a
```

* use enum with only value
```yaml
...
  aNode:
    type: treeNode
    properties:
      type:
        enum: [a]
```

However, i don't think these are good choices.

Any suggest? Or perhaps the spec needs improvement?
