### ISSUE TITLE
Define data types binding

### ISSUE THREAD

**Issue by jantoniucci** [raml-org/raml-spec#579]
Include an attribute at data type definition to describe the data binding to describe:
* data provided by the consumer for each method
* data returned by the server for each method

For example: we have a foo data type with two fields (id and name). The id is generated at server side and the name must be provided at creation time (POST) but is optional at update time.

```
types:
  foo:
    type: object
    properties:
      id:
        bindingDefinition:
          - method: "ALL"
            input: "NONE"
            output: "REQUIRED"
        type: string
        enum: ["PINLESS_ACTIVATION", "GLOBAL_ACTIVATION", "ECOMMERCE_ACTIVATION", "CASHWITHDRAWAL_ACTIVATION", "PURCHASES_ACTIVATION"]
        description: |
          Operational activation identifier.
      name:
        bindingDefinition:
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "OPTIONAL"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "REQUIRED"
        type: string
        description: |
          Operational activation description.
...

```

Having such a representation would make the life of definition authors much easier and would also be useful for a different number of goals, like:

* give consumers clear information on 
  * what to send mandatory / optional and at which verbs
  * what they expect to receive at the response 

* configure an API Gateway to validate inputs and outputs

* give to API developers clear information on what to expect to receive and what to send

Nowadays, to deliver this functionality we are using an annotation like these:

```
#%RAML 1.0 AnnotationTypeDeclaration
displayName: BindingDefinition
description: This annotation describes the binding definition in a method and input/output on a resource
usage: This annotation should be used in properties in data types indicating the binding definition
type: array
items:
  properties:
    method:
      type: string
      required: true
      description: This field defines to which method the binding applies
      enum: ["GET", "PATCH", "POST", "PUT", "DELETE", "ALL"]
    input:
      type: string
      required: true
      description: The binding related to the field when used as an input
      enum: ["OPTIONAL", "REQUIRED", "NONE"]
    output:
      type: string
      required: true
      description: The binding related to the field when used as an output
      enum: ["OPTIONAL", "REQUIRED", "NONE"]
...

```
Let's evolve this idea...

All feedback is welcome!
