### ISSUE TITLE
Routes should be namespaced

### ISSUE THREAD

**Issue by braco** [raml-org/raml-spec#58]
One of the issues we've had with choosing RAML and writing tools around it is that the routes aren't namespaced:

```
#%RAML 0.8
title: World Music API
baseUri: http://example.api.com/{version}
version: v1
traits:
  - paged: ...
  - secured: !include http://raml-example.com/secured.yml
/songs: ...

```

we can rewrite this as:

```
config: ...
config: ...
/route: ...
/route: ...
```

In addition to being sloppy taxonomically, this makes parsing very peculiar. You have to look at every key to see if it starts with a slash in order to determine the content type?

Would it not be better to just:

```
config: ...
config: ...
routes:
  /route: ...
  /route: ...
```

or

```
resources:
  /route: ...
```

In this case, enumerating routes just becomes a matter of listing the keys inside of routes:{...}

This also would open up different use cases in the future, like

```
routes: !include routes/*
```
