### ISSUE TITLE
how to reuse response pattern

### ISSUE THREAD

**Issue by chen2liang4** [raml-org/raml-spec#586]
I tried to define one resourceType for all responses of pagination query.
```
resourceTypes:
  pagedCollection:
    get:
      response:
        200:
          application/json:
          properties:
             page: number
             pageSize: number
             total: number
             items: <<item>>[]
```
Then I can apply to all resource which need pagination.
```
/books:
  type: { pagedCollection: {item: book} }
/authors:
  type: {pagedCollection: {item: author}}
```
Seems that it doesn't work, since I got one issue message in API workbench. No one really like to define these properties in each response, right? There must have be one solution, but what is it?
