### ISSUE TITLE
Default type for array items is not clearly defined

### ISSUE THREAD

**Issue by LorenaSoledad** [raml-org/raml-spec#587]
Having the following RAML as an example:

```yaml
#%RAML 1.0
title: Array default type
version: v1
types:
    MyType:
      type: array
```

You define a custom type which extends from an `array` type without using the array syntactic sugar, but you don't explicitly declare the `items` facet (Which is correct, because `items` [is defined as an optional facet](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#array-type)).

So:
 _Which should be the default type for the items in an array defined this way? (If `items` is not defined)_
