### ISSUE TITLE
It is not defined if Default media type is inherit in imported libraries

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-spec#592]
ResourceType defined inside an imported library. The root raml  file has a default media type (application/json). 
The resource type has a put method with a request body and this request body doesn't define the media type. 

Root file:
```
#%RAML 1.0
title: Example API
version: v1
mediaType: application/json

uses:
  resourceTypes: resourceTypes.raml
  

/entity:
  get:

```

Library file  looks like this:

```
#%RAML 1.0 Library
usage: Standard resourceTypes

resourceTypes:
  item:
    put:
      body:
          example: {"property":"value"}
```

This case is not documented on the RAML specification. It's not clear if the default media type is inherited in the imported libraries.

**Comment by sichvoge** [comment]
It should be if you, and only if you, declare `entity` to be of type `resourceTypes.item`.

```yaml
#%RAML 1.0
title: Example API
version: v1
mediaType: application/json

uses:
  resourceTypes: resourceTypes.raml
  

/entity:
  type: resourceTypes.item
  get:
```

The version where the resource type from the library is applied, should look like the following:

```yaml
#%RAML 1.0
title: Example API
version: v1
mediaType: application/json

/entity:
  put:
      body:
          example: {"property":"value"}
  get:
```

And the fully expanded version:

```yaml
#%RAML 1.0
title: Example API
version: v1
mediaType: application/json

/entity:
  put:
      body:
          application/json: 
            example: {"property":"value"}
  get:
```
