### ISSUE TITLE
User defined annotations on type properties

### ISSUE THREAD

**Issue by peterdmv** [raml-org/raml-spec#593]
Hi,

I'm investigating the feasibility of moving our REST API definition from RAML 0.8 to 1.0. In the current implementation of our service, we are using JSON schemas for validation on the server side and also for documentation (raml2html). 
We've added semantic information (**description**) to the properties of our schemas to help our users to build their REST clients. See an example below:

Schema:
```
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "id": "file://schema/Example#",
  "title": "Example",
  "description":"Definition of an Example",
  "type": "object",
  "properties": {
    "field1": {
      "description":"A short human readable string.",
      "type": "string",
      "pattern": "^[^,= \n\t+<>#;\\*\"]+$"
    }
   ...
}
```
Message:
```
{
  "field1": "Lorem ipsum",
  ...
}
```

We would like to add the same documentation to the properties using the new type system. Is there any way to do this with RAML 1.0? According to the RAML 1.0 specification annotations can only be added to specific target locations:

> Annotations can also be used to add properties to the built-in RAML nodes in certain locations within the RAML specification.

and

> The location within an API specification where annotations can be applied MUST be one of the target locations in the following Target Locations table. The targets are the locations themselves, not sub-properties within the locations;

Thanks!

**Comment by sichvoge** [comment]
Does that cover what you need?

```yaml
types:
  Example:
    description: Definition of an Example
    type: object
    properties:
      field1:
        description: A short human readable string.
        type: string
        pattern: ^[^,= \n\t+<>#;\\*\"]+$
```
