### ISSUE TITLE
The case of unknown parameters for filtering should be accounted for

### ISSUE THREAD

**Issue by jazzu** [raml-org/raml-spec#6]
Suppose you have a service, in which customers can define their own fields for data. Then there's the API which allows said customers to access and filter said data. Now, there are common parts in the API for all customers: the endpoints, pagination params, sorting params, etc. Only the filtering bits change according to customer specific choices.

Example:

```
A: /people?sort=surname&field_not_defined_for_B=some_filtering_value
```

vs.

```
B: /people?sort=surname&field_not_defined_for_A=some_other_filtering_value
```

How would this kind of API best described? Should there be some sort of catch-all queryParameters entry/reserved word/attribute to denote, that "this end point accepts possible customer-specific filter key-value pairs"?

This API representation question is an issue only when trying to present a general view of the API. Obviously, in specific customer cases the API description could be complemented with some sort of automatically generated, customer specific include file. The presence of said include tag might also suffice for such a clue for the reader:

```
# main_spec.raml
/people:
  get:
    queryParameters:
      query:
        description: A search string
        type: string
      !include customer_people_params.raml
```

This definition would mean, that /people endpoint accepts a parameter "query" and is _supposed_ to accept whatever is defined for a specific customer, even if specified file is not available.

What do you think?

---

On another note, is this GitHub issue tracker even right place to discuss this kind of things?
