### ISSUE TITLE
Allow more than scalar values for trait/recourceType parameters

### ISSUE THREAD

**Issue by Jo-Cat** [raml-org/raml-spec#608]
As the title says, I like to request to allow more than scalar values for trait/recourceType parameters.
For example to pass enum values to a trait. 

See my post in http://forums.raml.org/t/how-to-pass-raml-trait-parameters-for-enum-values/1761 for details to the need.

**Comment by Jo-Cat** [comment]
The following example of a trait should give you an impression of the use case:

```
#%RAML 1.0 Trait

usage: |
  Use this trait, if a return collection should be sorted by specific fields.

queryParameters:
  sort:
    description: |
     Sorts the response according to the values of the parameter. Values are supported fields of the response as stated in the enumeration.
     Standard is ascending; with a leading '-' in front of the field names it is descending.
    type: array
    items: 
      type: string
      enum: <<sortableFieldsEnum>>
    required: false
```
