### ISSUE TITLE
Annotation types should be usable in other annotation types

### ISSUE THREAD

**Issue by oberlies** [raml-org/raml-spec#611]
When I want to re-use types in an annotation declaration (e.g. for an annotation with nesting), I have to declare the type in the "types" section. I cannot completely define the annotation model in the "annotationTypes" section only.

Although this was originally [by intention](https://github.com/raml-org/raml-spec/issues/196#issuecomment-160449072), I would propose that this is changed. The problem with the current approach is that I am required to mix API types and API specification metatypes in the "types" section.

Example: This works:
```
#%RAML 1.0
title:
documentation:
  - title: Section
    content: Text in section
    (subsections):
      - title: Sub-section
        (subsections):
          - title: Sub-sub-section
            content: Text in sub-sub-section
annotationTypes:
  subsections:
    allowedTargets: DocumentationItem
    type: subsectionsMetaType
types:
  subsectionsMetaType:
    type: array
    items:
      type: object
      additionalProperties: false
      properties:
        title:
          type: string
        content:
          type: string
          required: false
        (subsections):
          type: subsectionsMetaType
          required: false
```

For a good separation of concerns, the following should IMHO also be valid:
```
#%RAML 1.0
title:
documentation:
  - title: Section
    content: Text in section
    (subsections):
      - title: Sub-section
        (subsections):
          - title: Sub-sub-section
            content: Text in sub-sub-section
annotationTypes:
  subsections:
    allowedTargets: DocumentationItem
    type: array
    items:
      type: object
      additionalProperties: false
      properties:
        title:
          type: string
        content:
          type: string
          required: false
        (subsections):
          type: subsections
          required: false
```
