### ISSUE TITLE
Correct Support for application/x-www-form-urlencoded not a JSON

### ISSUE THREAD

**Issue by rmzoni** [raml-org/raml-spec#613]
I´m trying to specify a RAML API contract that use content type application/x-www-form-urlencoded.

But the RAML specification treat this as JSON parameters in the body but I´m telling that the content type is an url encoded format not a JSON format.

For this specfication:
```
/helloWorld:
  post:
    body:
      application/x-www-form-urlencoded:
        properties:
          name:
            description: name on account
            type: string
            example: Naruto Uzumaki
          gender:
            enum: ["male", "female"]
```

I´m getting this:

```
{
  "name": "Naruto Uzumaki",
  "gender": "male"
}
```

But the correct would be this:
`name=Naruto Uzumaki&gender=male`
