### ISSUE TITLE
Question for validating union types

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#643]
Assume we have the following type definitions:

```yaml
types:
  EventType:
    type: object
    properties:
      eventTypeId: 
        type:  string
      eventTypeName:
        type:  string
      eventTypeCategory:
        enum:  [alert,notification,business,device,status]
  TemperatureSensorEvent:  
    type: EventType
    properties:
       temperature: number
       unit:  
         enum:  ['metric','imperial']
  HumiditySensortEvent:  
    type: EventType
  Event:
    type: object
    properties:
      payload:
        type:  TemperatureSensorEvent | TemperatureSensorEvent
```

And the following example:

```json
[
  {
    "payload": {
      "eventTypeId": "1234",
      "eventTypeName": "IoTEvent",
      "eventTypeCategory": "device",
      "temperature": "2.3"
    }
  }
]
```

What should be the type this example validates against? TemperatureSensorEvent or TemperatureSensorEvent?
