### ISSUE TITLE
Example RAML in Optional Properties section is invalid

### ISSUE THREAD

**Issue by eliaslevy** [raml-org/raml-spec#65]
The example resource type ins the [Resource Types and Traits / Optional Properties](https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#optional-properties) section is invalid.

The resource type has to optional methods, a post and a delete, both of which attempt to define a parameters in the body of a request (createAuthority and deleteAuthority respectively).  But the example defines these properties directly in the _body_ property, which is invalid.

Per the the spec:

> A method's body is defined in the body property as a hashmap, in which the key MUST be a valid media type.

Presumably the authors meant these parameters to be form parameters, as they are defined within a body.  If that is the case, then they should have been defined under the _formParameters_ property, which in turn should be under one of the two web form media types as keys in the _body_ property.

E.g.

``` yaml
#%RAML 0.8
title: Example of Optional Properties
resourceTypes:
  - auditableResource
      post?:
        body:
          application/x-www-form-urlencoded:
            formParameters:
              createAuthority:
                description: |
                  If the resource has a post method defined, expect a createAuthority
                  property in its body
      delete?:
        body:
          multipart/form-data:
            formParameters:
              deleteAuthority:
                description: |
                  If the resource has a delete method defined, expect a deleteAuthority
                  property in its body
```
