### ISSUE TITLE
Nullable type

### ISSUE THREAD

**Issue by carowright** [raml-org/raml-spec#665]
There is an example in nil type section that adds a question mark on the property type side: 

````
types:
  NilValue:
    type: object
    properties:
      name:
      comment: nil | string # equivalent to ->
                             # comment: string?
    example:
      name: Fred
      comment: # Providing a value or not providing a value here is allowed.
````

As it's mentioned in the comment, it's the same as:

````
types:
  NilValue:
    type: object
    properties:
      name:
      comment: string?
    
example:
      name: Fred
      comment: # Providing a value or not providing a value here is allowed.
````

This example can be found in [here](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#nil-type).
Besides this example there is no mention of how this construction works. So, either the example is invalid or this construction needs to be defined somewhere in the spec.

**Comment by sichvoge** [comment]
Hi Caro. It is defined, but not very clear indeed. Look into the first example of yours. the important line is:

```yaml
comment: nil | string # equivalent to ->
                      # comment: string?
```

As you can see, `comment: string?` is syntactic sugar and equivalent to `comment: nil | string`. 

I am sure we could clarify this a bit more. If you have time, may I ask you to send us a PR?

**Comment by alvassin** [comment]
@sichvoge seems to be a bug.

according to `nil | string` equals to `comment?` means that `comment` is optional, but it should be not like that.

technically comment must be required, but can have as null as string values as well.

**Comment by jstoiko** [comment]
@alvassin: `comment?` and `string?` are two different things.

```raml
comment: nil | string
```
is equivalent to:
```raml
comment: string?
```
and means that the value of `comment` can be `null` whereas:
```raml
comment?: string
```
means that `comment` is not required.

We could also have:
```raml
comment?: string?
```
which would mean that `comment` can be `null` and is also not required.

**Comment by sheamunion** [comment]
@jstoiko I'm trying to create a required, nullable property with a user-defined type in a separate file. For some reason, my IDE (MuleSoft Anypoint Studio) considers this invalid. Am I trying to do something invalid or is my IDE incorrect?

**Response.raml**
```
#%RAML 1.0 DataType

type: object
properties:
  error: nil | !include Error.raml
```

**Error.raml**
```
#%RAML 1.0 DataType

type: object
properties:
  code: string
  message: string
```
