### ISSUE TITLE
schemas property of the example in the Resource Types and Traits / Parameters section is wrong

### ISSUE THREAD

**Issue by eliaslevy** [raml-org/raml-spec#67]
It shows the schemas property as a map, instead of an array of maps:

``` yaml
#%RAML 0.8
title: Example API
version: v1
mediaType: application/json
schemas:
  users: !include schemas/users.json
  user: !include schemas/user.json
```
