### ISSUE TITLE
Issue with example comment in the spec

### ISSUE THREAD

**Issue by jarrodek** [raml-org/raml-spec#674]
```yaml
types:
  NilValue:
    type: object
    properties:
      name:
      comment: nil | string # equivalent to ->
                             # comment: string?
    example:
      name: Fred
      comment: # Providing a value or not providing a value here is allowed.
```

The comment `# comment: string?` is invalid. There's no such construct in RAML. It should be `# comment?: string`.
This is actually serious. Our clients started using this notation and RAML parse accepts it as a union type of the type an nill value [sic!!]. This breaks whole RAML API tooling when at least some of the properties are marked this way because parser creates an union for each combination. That explodes exponentially and the output kills processes for parsers or renderers (like api console) because of lack of memory.
