### ISSUE TITLE
Please clarify how multiple inheritance should work.

### ISSUE THREAD

**Issue by alvassin** [raml-org/raml-spec#677]
Hello. According to documentation, i can use only same primitive types for multiple inheriting.

What about number & integer? Can i mix them? Official parser for now allows that definition:
```
#%RAML 1.0
title: Types example
types:
  Base:
    type: [integer, number]
    example: 3
```
Result: Base type definition would be allowed, but example would require integer only values. These are primitive types.

What about any and other primitives?
```
```
