### ISSUE TITLE
xml:name when xml:wrapped is true

### ISSUE THREAD

**Issue by KevinMitchell** [raml-org/raml-spec#682]
The spec contains the following example:

```
types:
  Person:
    properties:
      addresses:
        type: Address[]
        xml:
          wrapped: true 
```
If I also include a name node, e.g. `name: foo`, which element name does this override, the outer element name or the inner one?  And how do I override the other one? It looks like we have two names, and only one name node, which is why I was expecting the wrapped node to be of string type, rather than a boolean.
