### ISSUE TITLE
Support for metadata in examples

### ISSUE THREAD

**Issue by agseco** [raml-org/raml-spec#688]
As of today it seems a set of example is supported as follows:

```
description: Booking related endpoints.
/book:
  post:
    displayName: Create Booking
    description: |
      This endpoint is intended to create a booking with passengers and contact information,
      as well as with payment details.
    body:
      application/json:
        examples:
          example1: !include example1.json
          example2: !include example2.json
          example3: !include example3.json
```

I really miss the possibility of adding metadata to my examples, such as description, to make them richer and explanatory.

Please pardon me if I'm being too naive with my suggestion or it's somehow already supported and haven't figured it out (at least could not find it in [the spec](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#defining-examples-in-raml)).
