### ISSUE TITLE
Enum values

### ISSUE THREAD

**Issue by Arnau-Codern** [raml-org/raml-spec#696]
Hi, I'm having some when generating enum values and generating classes with these enums as values.
Context: I'm generating the models of an API.
The following RAML specification generates me the enum EnumType1, and the class WhateverClass, but the class WhateverClass does not have the field EnumField.
```
EnumType1:
    description: description of enum type
    enum:
      - VALUE1
      - VALUE2
    
  WhateverClass:
    properties:
      EnumField:
        description: This field is of type EnumType1
        type: EnumType
        required: true
      WhateverOtherField:
        description: Just another field
        type: string
        maxLength: 40
        required: true
```
I know I could define the enum at the field level, something like:
```
WhateverClass:
    properties:
      EnumField:
        description: This field is of type EnumType1
        enum:
      - VALUE1
      - VALUE2
      WhateverOtherField:
        description: Just another field
        type: string
        maxLength: 40
        required: true
```
But I would like to centralise the definition of the enum as I need to reuse it many times.

Any help would be greatly appreciated.

AC
