### ISSUE TITLE
Clarify use of type-specific facets in a union type

### ISSUE THREAD

**Issue by jstoiko** [raml-org/raml-spec#711]
The [description of the union type](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#union-type) makes no mention of how to apply facets and the restrictions thereof.

### Proposed clarification
- Add that `a union type MAY have any of its super types facets as long as all super types participating in that union accept those facets`

#### Examples
```
types:
  Foo: number
  Bar: integer
  FooBar:
    type: Foo | Bar
    minimum: 1 # valid because both "Foo" (number) and "Bar" (integer) all accept "minimum"
```
```
types:
  Foo: number
  Bar: integer
  Qux: string
  FooBarQux:
    type: Foo | Bar | Qux
    minimum: 1 # invalid because "Qux" (string) does not accept the "minimum" facet
```
```
types:
  Foo: number
  Bar: integer
  Qux:
    type: string
    facets:
      minimum: number
  FooBarQux:
    type: Foo | Bar | Qux
    minimum: 1 # valid because "Qux" (string) has a user-defined facet "minimum"
```
