### ISSUE TITLE
Discriminator expected behavior question

### ISSUE THREAD

**Issue by jam01** [raml-org/raml-spec#717]
Consider the following RAML
```
types:
  event:
    type: object
    discriminator: eventType
    properties:
      eventType: string

  fooEvent:
    type: event
    discriminatorValue: foo
    properties:
      bar: string

/resource:
   post:
     body:
       application/json:
         type: fooEvent
```

**Expected behavior**
`/resource` should accept a value such as:
`{"eventType":"foo", "bar":"val"}`

and reject a values such as:
`{"eventType":"not-foo", "not-bar":"val"}`
`{"not":"acceptable"}`
`{}`

Is that correct?

I'm trying to understand exactly what can be expected of a data type validation library. I opened an [issue with raml-java-parser](https://github.com/raml-org/raml-java-parser/issues/620) and would like to find out if maybe I misunderstood what should be valid and invalid.

Thanks!
