### ISSUE TITLE
Add displayName for methods

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#74]
This will allow to give semantic names to methods, and simplify SDK or richer client generation.

Example:
```yaml
#%RAML 0.8
title: My Sample API
/files:
  get:
    displayName: getFiles
```
