### ISSUE TITLE
[Question] How to specify a facet for a nullable type?

### ISSUE THREAD

**Issue by GauthierPLM** [raml-org/raml-spec#757]
I have a type for which I would like to specify that `maxLength` is 165. However, the type being a nullable string (`string | nil`), specifying the facet like I did in the example is not authorised (according to Anypoint' Design Center validation).

What is the right way to specify the maxLength?

```yaml
#%RAML 1.0 DataType
type: object
properties:
  url:
    type: string | nil
    maxLength: 165
    required: false
```
