### ISSUE TITLE
Add support for JSONP

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#76]
In order to support JSONP a new `jsonp` property should be added to methods. This property MUST be interpreted in the following way:
- If present in a method, this operation can be called using JSONP
- If the method is other than `get`, the URI can be called and the `method` property in the `jsonp` property must exist
- RAML processors MUST:
  - If the method is different from `get`, they MUST use the `method` property and send the method's name as a URI parameter
  - If the `body` property is defined, and the method defines a body, the body must be sent as a URI parameter (URL encoded)

| Property Name | Description |
| --- | --- |
| `callback` | The name of the URI parameter used by the API to indicate the name of the Javascript function to call on responses. |
| `method` | The name of the URI parameter to submit the HTTP method (if different than GET) |
| `body` | The name of the URI parameter to submit the body of the request |

``` yaml
#%RAML 0.8
title: My Sample API
baseUrl: http://myapi.io
/files:
  description: return a list of file metadata
  get:
    jsonp:
      callback: callback
  post:
    description: create a file
    jsonp:
      callback: callback
      method: APImethod
      body: body
    body:
      example: |
        {
          'name': 'my-file-name.txt',
          'created-date': 1409147946
        }
```

With this example, a request to retrieve file resources MUST be interpreted as a GET to `http://myapi.io/files?callback=processResponse`.
With the same example, a file resource creation MUST be interpreted as a GET to /files
