### ISSUE TITLE
What is the raml code for this?  Students: [ { Name: Amritha } { Name: Anagha } ]

### ISSUE THREAD

**Issue by mundeko** [raml-org/raml-spec#764]

**Comment by GauthierPLM** [comment]
This is the definition of a `Students` property:

```YAML
Students:
  type: array
  items:
    type: object
    properties:
      Name:
        type: string
```

If this solve your issue, you can close this Github issue.
