### ISSUE TITLE
Add support for headers in JSONP

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#77]
_This is separate from the main JSONP discussion, because I have not seen a standard for this anywhere_

Add a `headers` property to `jsonp`, if present:
- RAML processors must send any headers defined for the method as a JSON encoded object, where each key in the object is a header.

| Property Name | Description |
| --- | --- |
| `headers` | The name of the URI parameter to submit any extra headers needed by the API |

``` yaml
#%RAML 0.8
title: My Sample API
baseUrl: http://myapi.io
/files:
  description: return a list of file metadata
  get:
    jsonp:
      callback: callback
      headers: api-headers
```
