### ISSUE TITLE
A reusable 'pageable' trait that can allow reuse of query parameters and result

### ISSUE THREAD

**Issue by marke-apexit** [raml-org/raml-spec#773]
I have been trying to figure out how to leverage traits to implement a reusable 'paging' trait.

I understand how to introduce the query parameters for a reusable 'pageable' definition for GET operations:

```yaml
traits: 
  pageable: 
    queryParameters:
      offset?:
        type: integer
        default: 0
        minimum: 0
        required: false
      limit?:
        type: integer
        default: 50
        minimum: 1
        maximum: 500
        required: false
```

However, I also need to return paging result information in each result that supports the pageable trait.  Something like the example below where the "paging" object is inserted in the JSON result.

```json
{
  "items": [
     { "foo": "xyzzy",
        "bar": "plugh"
     },
     { "foo": "plover" }
  ],
  
  "pagingInfo": {
    "count": 2,
    "hasMore": false,
    "limit": 50,
    "offset": 0,
  }
}
```

Is there any way in RAML to create a reusable 'pageable specfication that can be reused across all of my GET operations for both the query parameters and the paging info results?
