### ISSUE TITLE
It'd be nice if we could specify json-schemas as structured data

### ISSUE THREAD

**Issue by radix** [raml-org/raml-spec#8]
Since json is a subset of YAML, it would be nice if we could specify the json schemas in-structure with the RAML. These two examples would become possible:

```
/{songId}:
  get:
    body:
      application/json:
        schema: {
          "$schema": "http://json-schema.org/schema",
          "type": "object",
          "description": "The canonical song representation",
          "properties": {
            "title":  { "type": "string" },
            "artist": { "type": "string" }
          },
          "required": [ "title", "artist" ]
        }
```

(Notice the lack of the | in the schema object)

Or, more interestingly,

```
/{songId}:
  get:
    body:
      application/json:
        schema:
          $schema: "http://json-schema.org/schema"
          type: "object"
          description: "The canonical song representation"
          properties:
            title:
              type: "string"
            artist:
              type: "string"
          required:
            - "title"
            - "artist"
```

This would allow the json-schema to "fit in" better with the RAML schema, in addition to making available the use of things like !include for subsections of a json-schema. Just an idea!
