### ISSUE TITLE
Allow Dynamic, parameter-driven !includes

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#84]
The following syntax for `!includes` should be allowed in resource types and traits.

``` yaml
#%RAML 0.8
title: My Sample API
resourceTypes:
  - collection:
      get:
      post:
        body:
          example: !include <<resourcePathName!singularize>>.json
```
