### ISSUE TITLE
Allow arrays and maps as resource types and traits parameters

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#85]
In order to have more powerful traits and resource types, we should allow trait and resource types parameters be scalars, arrays, **and** maps, this will allow resource types like the following:

```yaml
#%RAML 0.8
title: My Sample API
traits:
  - orderBy:
      description: Order by field
      type: string
      enum: <<filterValues>>
      required: false
/people:
  is: [orderBy: { filterValues: ['age', 'height'] } ]
```

**Comment by sichvoge** [comment]
This could be great! I haven't seen anything in our current draft @aldonline @usarid. Shall we moved that to the candidates?

**Comment by aldonline** [comment]
We will allow non-string types as long as they are explicitly typed or can be inferred from context

**Comment by sichvoge** [comment]
The example above seems to be very wrong. Are we actually referring to the following:

```yaml
#%RAML 1.0
title: My Sample API
traits:
  orderBy:
    queryParameters:
      orderBy:
        description: Order by field
        type: string
        enum: <<filterValues>>
        required: false
/people:
  is: [orderBy: { filterValues: ['age', 'height'] } ]
```
