### ISSUE TITLE
Clarify resource precedence when two URIs collide

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#87]
When two resources have the same relative URI, and there are no URI parameters in the URIs, then the RAML should be invalid:

```yaml
#%RAML 0.8
title: My Sample API
/users:
  me:
    get:
/users/me:
  post:
```

When there are URI parameters in the relative URIs, it is assumed that the API routing implementation can handle the ambiguity. In such cases, to resolve ambiguity, resources defined earlier in the RAML spec take precedence over resources declared later. In the following example, the definition of the route `/users/me` takes precedence over `/users/{id}`, and both routes are considered to be different resources.

```yaml
#%RAML 0.8
title: My Sample API
/users/me:
  get:
/users:
  {id}:
    get:
```
