### ISSUE TITLE
Traits parameters should be passed with yaml syntax

### ISSUE THREAD

**Issue by cybertk** [raml-org/raml-spec#88]
In RAML 0.8, traits parameters are written in javascript/json syntax, like

``` raml
/books:
  type: { searchableCollection: { queryParamName: title, fallbackParamName: digest_all_fields } }
  get:
    is: [ secured: { tokenName: access_token }, paged: { maxPages: 10 } ]
```

The traits parameters should be written in yaml syntax also in order to get consistent context.

``` raml
/books:
  get:
    is: [
          {
            secured:
              tokenName: access_token
              paged:
                maxPages: 10
          }
        ]
```

Or more easier and clear format

```
/books:
  get:
    is:
      secured:
        tokenName: access_token
        paged:
          maxPages: 10
      paged:
        limit: 20
```
