### ISSUE TITLE
Parameter enum of non-strings?

### ISSUE THREAD

**Issue by eliaslevy** [raml-org/raml-spec#92]
The Named Parameters / enum section of the spec states

> (Optional, applicable only for parameters of type string) The enum attribute provides an enumeration of the parameter's valid values. This MUST be an array. If the enum attribute is defined, API clients and servers MUST verify that a parameter's value matches a value in the enum array.

Since the enum property is only valid on parameters of type string, it reasons that the enum array can only contain strings.

Which makes the following portion of the Twitter RAML API file rather curious:

```
  queryParameters:
    include_entities:
      description: The entities node will not be included when set to false.
      enum: 
        - 0
        - 1
        - true
        - false
        - t
        - f
```

These are not all strings according to YAML. So it the spec wrong or it this RAML file and the tooling that accepts it incorrect?
