### ISSUE TITLE
Validations for form parameters of type `file`

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#94]
RAML 1.0 should allow the applicability of minimumLength and maximumLength for parameters of type `file`, RAML processors MUST interpret them as the length in BYTES of the file.

It should also include a new property: `fileTypes`, which should be a list of valid content-type strings for the file. The file type `*/*` should be a valid value.

In the following example the named parameter `userPicture` can be as large as 300KB, and must be either a JPEG or PNG image, while the `file` named parameter must be smaller than 1MB and can be of any type.

```yaml
#% RAML 1.0
title: My Sample API
types:
  userPicture:
    type: file
    fileTypes: ['image/jpeg', 'image/png']
    maximumLength: 307200
  file:
    type: file
    fileTypes: ['*/*']
    maximumLength: 1048576
```
