### ISSUE TITLE
Allow for custom types and add `types` root level property

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#96]
RAML 1.0 should have a way to define named parameter types as a top level entity for later reuse.

In the following example, a named parameter type called userName is defined and later used to validate a uriParameter.

```yaml
#%RAML 0.8
title: My Sample API
types:
  userName:
    type: string
    example: aUserName
    validationPattern: \w{1,15}
/users/{id}:
  uriParameters:
    id:
      type: userName
```

A root level type cannot overwrite RAML defined types (such as `string`, `number`, etc)
