### ISSUE TITLE
Fix errors with the Authorization Grants for OAuth 2.0

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#99]
The list should be clear regarding the Authorization Grant names:
 - Authorization code grant: `authorization_code`
 - Resource owner password credentials grant: `password`
 - Client credentials grant: `client_credentials`
 - Implicit grant: `implicit`
 - Refresh token grant: `refresh_token`

```yaml
#%RAML 0.8
title: My Sample API
securitySchemes:
    - oauth_2_0:
        description: |
            OAuth 2.0 implementation.
        type: OAuth 2.0
        settings:
          authorizationUri: https://www.myapi.com/1/oauth2/authorize
          accessTokenUri: https://www.myapi.com/1/oauth2/token
          authorizationGrants: [ authorization_code, password, client_credentials, implicit, refresh_token ]
```
